// Changelog/updates da plataforma
export interface UpdateItem {
  versao: string
  data: string
  titulo: string
  descricao: string
  tipo: 'novo' | 'melhoria' | 'correcao' | 'agente'
  emoji: string
}

export const CHANGELOG: UpdateItem[] = [
  { versao: '10.1.0', data: '2026-07-22', titulo: 'BOOM v10.1 — 200+ AGENTES, SQL corrigido, +8 alternativas, novo blog', descricao: '🔥 V10.1 BOOM no ar! Chegamos a 200+ agentes IA. Novos 25 agentes: Carta de Reembolso CDC, Calculadora de Tributos PF/PJ (Simples/Lucro Real/Presumido/IRPF), Contrato de Prestação de Serviços, Auditor de Anúncios Meta/Google, Criador de Quiz Viral, Audience Lab (20 públicos segmentados), Roteiro Reels/TikTok 15s, Legenda Instagram Autêntica, Sequência Black Friday Completa (7 emails), Resposta a Críticas/Reclamações, Descrição de Produto para Amazon/Mercado Livre/Magalu/Shopee, Polos Privados de Afiliado, Termos de Uso + Política de Privacidade LGPD, Script Pré-Julgado (9 SIMs antes do preço), Calendário Editorial 30 dias, Oferta Irresistível (Hormozi-style), Gerador de Títulos Virais (20 variações), Sequência WhatsApp 7 mensagens, Persona Profunda, Checkout Kick Booster (+20% conversão), Email Carrinho Abandonado 3-part, História de Sucesso/Case, FAQ 20 objeções, Calculadora PLR/MRR/White Label, Planilha de Gastos Doméstica. Corrigidos erros no SQL (função _add_col genérica, aspas quebradas, blocos PERFORM). +8 páginas SEO de alternativas a concorrentes (Braip, Ticto, Hubla, Payt, Perfect Pay, Yampi, Doppus, LastLink). Novo post de blog "Como ganhar dinheiro com IA em 2026". Todas as menções de "180+ agentes" atualizadas para "200+ agentes". Build: 0 erros de tipo, 800+ páginas estáticas.', tipo: 'novo', emoji: '🔥' },
  { versao: '10.0.0', data: '2026-07-21', titulo: 'MONSTER v10 — +22 agentes IA, SEO massivo, taxa zero', descricao: '🚀 LANÇAMENTO v10 MONSTER: +22 NOVOS agentes IA (total 180+) incluindo Black Friday Playbook, Lead Magnet Pro, TikTok & Reels Scripts, SEO Local por cidades, Calculadora ROI Ads, Quiz de Upsell (+40% ticket), Prompts Canva/Midjourney, Auditoria CRO, Email Swipe File, Funil WhatsApp, Instagram Grid, Pedido de Review, Estrutura Página de Vendas, Pitch Podcast, Auditoria CRO, Campanha KD Points, Reescrever PLR, Checklist Lançamento 30 dias, Gerador VSL, Reduzir Churn, Teste de Webhook e Calculadora Dutching. Páginas SEO de cauda longa /alternativa/hotmart, /alternativa/kiwify, /alternativa/monetizze, /alternativa/eduzz, /alternativa/ggmax, /alternativa/microsoft-store, /melhor-plataforma-produtos-digitais, /taxa-zero (0% nas primeiras 5.000 vendas!), /blackfriday, /programa-afiliados. 3 posts de blog otimizados para Google. Sitemap dinâmico com produtos reais do Supabase. Total de páginas estáticas geradas: 787.', tipo: 'novo', emoji: '🚀' },
  { versao: '9.3.0', data: '2026-07-21', titulo: 'LUCRO REAL — +12 agentes, página de Saque, valor percebido', descricao: '12 NOVOS agentes (total 157): PitchVenda, Defesa Chargeback, Respondedor de Reviews, Precificação Dinâmica, Hook de Anúncio, Criativo de Anúncio, PitchDeck, Minuta Contrato Afiliado, NPS Follow-Up, Sequência Pós-Venda, Gerador de Bônus, Calculadora Valor Percebido.', tipo: 'novo', emoji: '💸' },
  { versao: '9.2.0', data: '2026-07-21', titulo: 'LUCRO REAL — +12 agentes de venda e custos', descricao: 'Custos Reais de Venda (Stripe+PIX+KIYVO+CAC), Criador de Order Bump, OTOSequencia, ScriptSPN, RefundDesescalador, ProfitFirstBR, GiftCardCreator, CashbackEngine, LeadMagnetPro, TicketMedioAumento (10 estratégias), WebinarRoteiro 90min, 12 Perguntas que Fecham.', tipo: 'novo', emoji: '💰' },
  { versao: '9.1.0', data: '2026-07-21', titulo: 'MONETIZACAO TOTAL — +12 agentes, pagina Renda Extra', descricao: '12 novos agentes: Simulador de Saque, Preco Assinatura, Upsell Carrinho, Cupom Relampago, Upgrade Plano, Venda Cruzada, Boas-Vindas Primeira Compra, ROI de Anuncios, Black Friday Playbook, MRR Calculator, Script Lancamento 7 dias, Copy Lancamento. Pagina /renda-extra com 6 formas de ganhar dinheiro. Calculadora de ganhos interativa. Total: 133 agentes.', tipo: 'novo', emoji: '💰' },
  { versao: '9.0.0', data: '2026-07-21', titulo: 'JUSTO & LUCRATIVO — Taxas transparentes e 30 novos agentes', descricao: 'A KIYVO agora cobra no MAXIMO 8% + R$0,50 (teto de R$50) — a taxa mais justa do Brasil. Nova pagina /transparencia, /calcular-taxas, /boost. SQL v9 com subscriptions, withdrawals, bundles, giftcards, loyalty tiers, flash sales, afiliados completos.', tipo: 'novo', emoji: '🚀' },
  { versao: '9.0.0', data: '2026-07-21', titulo: 'JUSTO & LUCRATIVO — Taxas transparentes e 30 novos agentes', descricao: 'A KIYVO agora cobra no MÁXIMO 8% + R$0,50 (teto de R$50) — a taxa mais justa do Brasil comparado a Hotmart (10,99%+R$1), Eduzz (9,9%+R$1), Kiwifi (12%+R$1) e Microsoft Store (30%). Nova página /transparencia, /calcular-taxas com lucro real, /boost para impulsionar produtos, SQL v9 com subscriptions, withdrawals, bundles, giftcards, loyalty tiers, flash sales, afiliados completos, 30 NOVOS agentes de vendas (LucroMax, UpsellMax, CheckoutMax, ScarcityPro, ProvaSocialPro, EmailBoasVindas, LeadMagnet, WhatsAppVendas, OfertaRelampago, BundleCriador, FAQObjetor, QuizVendas, CaptionVendas, RefundMinimizer, AfiliadorPro, MetodoHero, NomesDominio, ChecklistVP, ClientePraVida, ScriptBotResposta, ViralLoop, KDCalculator, ABTestIdeas, SocialCopy, CancelaSaver, SEOTags, PrecoGuerra, CarrinhoAbandonado, PrecificacaoInteligente, GarantiaExpress). Total: 121 agentes.', tipo: 'novo', emoji: '🚀' },
  { versao: '9.0.0', data: '2026-07-21', titulo: 'Sistema de Boost de produtos (receita da plataforma)', descricao: 'Agora vendedores podem impulsionar produtos com Boost Relâmpago (R$4,90/6h), Diário (R$14,90/24h), Semanal (R$69,90/7d) ou Premium (R$199,90/30d) — sem assinatura, sem surpresas.', tipo: 'novo', emoji: '⚡' },
  { versao: '9.0.0', data: '2026-07-21', titulo: 'Sistema de saques/withdrawals', descricao: 'Saque mínimo R$30 com taxa fixa R$0,99 — PIX em 1 dia útil, transparência total.', tipo: 'novo', emoji: '💸' },
  { versao: '9.0.0', data: '2026-07-21', titulo: 'Loyalty tiers: Bronze, Prata, Ouro, Diamante', descricao: 'Descontos progressivos em taxas (até 20%), cashback de KD Points em dobro e benefícios exclusivos para clientes frequentes.', tipo: 'novo', emoji: '💎' },
  { versao: '9.0.0', data: '2026-07-21', titulo: 'Bundles/combos e flash sales', descricao: 'Crie combos com desconto progressivo de produtos. Promoções relâmpago nativas da plataforma.', tipo: 'novo', emoji: '📦' },
  { versao: '9.0.0', data: '2026-07-21', titulo: 'Afiliados completo', descricao: 'Links únicos por produto, rastreamento de cliques, comissões configuráveis por plano, saque mínimo R$50.', tipo: 'novo', emoji: '🤝' },
  { versao: '8.10.0', data: '2026-07-21', titulo: '+18 agentes IA — total de 91', descricao: 'HeadlineAnalyzer, EmailSequencia, BlogIdeia, PAS Copy, PodcastScript, FaturaProjeção, WhatsAppBoasVindas, InvoiceGen, TestimonialCrafter, PLRSearch, WarmupPlan, AffiliateProposal, FAQAuto, ReferralBadge, RiskScore, FeedbackInterpreter, ValeDesconto, ContratoRápido.', tipo: 'agente', emoji: '🤖' },
  { versao: '8.10.0', data: '2026-07-21', titulo: 'Novos agentes invisíveis de sistema', descricao: 'RiskScore antifraude automático, FeedbackInterpreter para tickets, ChurnPredictor para retenção, AutoMod de comentários, DynamicPricing, ContentAuditor LGPD.', tipo: 'melhoria', emoji: '🤖' },
  { versao: '8.10.0', data: '2026-07-21', titulo: 'Header com atalho para notificações', descricao: 'Sino de notificações adicionado ao menu de usuário, link rápido para /notificacoes.', tipo: 'melhoria', emoji: '🔔' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'NEO EVOLUTION — 73 agentes IA', descricao: '22 NOVOS agentes: AutoMod, DynamicPricing, ChurnPredictor, SmartCart, RetargetPredictor, TitleScorer, ThumbnailMaker, ScriptShort, OfferStacker, VoicePrep, LandingChecker, ReviewReplier, CompetitorMonitor, SocialProofEngine, QuizFunnel, SEOBriefing, ContentAuditor, EmojiPicker, LaunchChecklist, PersonaCraft, UrgenciaMaker, MetricsAnalyzer, WebhookTester, QRGenerator, SenhaForge, ValidatorBR, ContadorRegressivo, GradeHorários, CTAMaker, NPSAnalyzer, SlugMaker.', tipo: 'agente', emoji: '🤖' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'SQL idempotente v8.9', descricao: 'Novas tabelas: notifications, product_reviews, comments, follows, cart_items, wishlist, referrals, affiliates, wallet_transactions, reports, coupon_usage, price_alerts, price_history, ab_tests, newsletter_subs, audit_log, saved_prompts, shop_sections, clicks_events.', tipo: 'novo', emoji: '🗄️' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'Sistema de avaliações de produtos', descricao: 'Reviews com nota 1-5, fotos, prós/contras, respostas do vendedor e média automática no produto.', tipo: 'novo', emoji: '⭐' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'Carrinho persistente com upsell', descricao: 'SmartCart calcula combos, KD Points, descontos e sugere upsell/cross-sell automaticamente.', tipo: 'novo', emoji: '🛒' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'Prova social em tempo real', descricao: 'SocialProofEngine gera notificações "fulano de SP comprou há 2 min" para aumentar conversão.', tipo: 'novo', emoji: '👥' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'Quiz funil de vendas', descricao: 'QuizFunnel cria quizzes de 3-8 perguntas para segmentar leads e apresentar oferta certa.', tipo: 'novo', emoji: '❓' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'Auditoria LGPD/CDC automática', descricao: 'ContentAuditor detecta promessas ilegais em produtos e páginas para evitar bloqueios de anúncios.', tipo: 'melhoria', emoji: '⚖️' },
  { versao: '8.9.0', data: '2026-07-21', titulo: 'Gatilhos no banco', descricao: 'Triggers automáticos: atualiza rating do produto, contadores de seguidores, notificações de review, garantia de referral_code.', tipo: 'novo', emoji: '⚡' },
  { versao: '8.7.0', data: '2025-01-15', titulo: '10 NOVOS agentes IA', descricao: 'ReviewResponder, ScarcityForge, TitleSplit, ScriptForge, EmailForge, FunnelForge, DescFetcher, TaxCalc, CompetidorRadar e BonusForge.', tipo: 'agente', emoji: '🤖' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Sistema de Conquistas', descricao: '20 badges para ganhar, XP, níveis e KD Points recompensando compras, vendas, avaliações e indicações.', tipo: 'novo', emoji: '🏆' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Calculadora de Lucro Real', descricao: 'Veja lucro LÍQUIDO com taxas KIYVO, gateway, IRPF/Simples, frete e CAC — direto em /calculadora-lucro.', tipo: 'novo', emoji: '🧮' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Análise de concorrente', descricao: 'Cole a descrição do concorrente no DescFetcher e receba uma versão 10x melhor em segundos.', tipo: 'novo', emoji: '🔍' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Gerador de funis de venda', descricao: 'FunnelForge cria funis perpétuos, oficina 24h, tripwire e lançamento sniper completos.', tipo: 'novo', emoji: '🎯' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Roteiros Reels/TikTok automáticos', descricao: 'ScriptForge gera hook, cenas, CTA, hashtags e música sugerida para vídeos que viralizam.', tipo: 'novo', emoji: '🎬' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Gatilhos de escassez', descricao: 'ScarcityForge cria badges de relâmpago, contadores e prova social para aumentar conversão.', tipo: 'novo', emoji: '🔥' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Bônus irresistíveis', descricao: 'BonusForge gera pacotes de bônus que triplicam o valor percebido da sua oferta.', tipo: 'novo', emoji: '🎁' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'E-mail marketing em 1 clique', descricao: 'EmailForge escreve sequências de boas-vindas, carrinho abandonado, lançamento e pós-venda.', tipo: 'novo', emoji: '📧' },
  { versao: '8.7.0', data: '2025-01-15', titulo: 'Split test de títulos', descricao: 'TitleSplit gera 6 variações de título usando fórmulas de copywriting com CTR estimado.', tipo: 'novo', emoji: '✍️' },
  { versao: '8.6.0', data: '2025-01-12', titulo: '13 agentes IA iniciais', descricao: 'Kiya, BannerForge, CopyMaster, PriceMaster, ProductHunter, ReviewShield, AdOptimizer, ReplyMaster, SEOBoost, SEOScore, Translate, PromoGen + FreelanceMatch.', tipo: 'agente', emoji: '🤖' },
  { versao: '8.6.0', data: '2025-01-12', titulo: 'Sistema de cupons', descricao: 'Cupons percentuais e fixos com validade, limite de uso e afiliados.', tipo: 'novo', emoji: '🏷️' },
  { versao: '8.6.0', data: '2025-01-12', titulo: 'Freelance com escrow', descricao: 'Bids, escrow e match automático entre clientes e freelancers.', tipo: 'novo', emoji: '💼' },
]

export function getLatestUpdates(limit = 6) {
  return CHANGELOG.slice(0, limit)
}

export function getUpdatesByType(tipo: UpdateItem['tipo']) {
  return CHANGELOG.filter(u => u.tipo === tipo)
}
