// ─────────────────────────────────────────────────────────────
// Email Temp Block v0.0.1 — Bloqueio de emails temporários/descartáveis
// 200+ domínios conhecidos + verificação MX + padrões suspeitos
// ─────────────────────────────────────────────────────────────

// Lista de mais de 200 domínios de email temporário conhecidos
const TEMP_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '20minutemail.com', '20minutemail.it',
  '30minutemail.com',
  '5mail.cf', '5mail.ml', '5mail.ga',
  'abcmail.ml', 'abcmail.ga', 'abcmail.cf',
  'admincpan.com', 'agtx.cf', 'ahrenhei.ml',
  'airmail.cc', 'airpost.cc',
  'akmail.com',
  'anonaddy.me', 'anonaddy.com',
  'anonymail.dk',
  'anonymous4.us', 'anonymousemail.me',
  'armyspy.com',
  'auti.st', 'autotw.com',
  'bcaoo.com', 'bccano.com',
  'bigprofessor.so',
  'binka.me',
  'biotics.ws',
  'bizsearch.info',
  'blacksailor.com',
  'blip.ch',
  'bluewerks.com',
  'brmailing.com',
  'bumpymail.com',
  'c2.hu',
  'cachedot.net',
  'cellurl.com',
  'centermail.com', 'centermail.net',
  'chammy.info',
  'cheaphub.net',
  'chogmail.com',
  'cincurade.net',
  'ckdevelop.org',
  'clandest.in',
  'cliptik.net',
  'cloudmail.xyz',
  'clrmail.com',
  'cmail.com',
  'cnn.coms.hk',
  'cobarekyo.ml',
  'compareshippingrates.org',
  'cool.fr.nf',
  'correo.blogos.net',
  'cosmorph.com',
  'courriel.fr.nf',
  'crapmail.org',
  'cubiclink.com',
  'curryworld.de',
  'dacoolest.com',
  'dangh.xyz',
  'daymail.life', 'daymail.space', 'daymailonline.com',
  'deadaddress.com',
  'deadspam.com',
  'delikkt.de',
  'derkombi.de',
  'despam.it', 'despammed.com',
  'devnullmail.com',
  'diginew.com',
  'discard.email', 'discardmail.com', 'discardmail.de',
  'dishcatfish.com',
  'dodgeit.com',
  'dodgemail.de',
  'dodgit.com', 'dodgit.org',
  'dontreg.com',
  'drdrb.com', 'drdrb.net',
  'dropcake.com',
  'dropmail.me',
  'dudmail.com',
  'dump-email.info',
  'dumpmail.com', 'dumpmail.de',
  'dumpyemail.com',
  'e-mail.com', 'e-mail.org',
  'e4ward.com',
  'easytrashmail.com',
  'edv.to',
  'email-fake.com', 'email-fake.cf', 'email-fake.ga', 'email-fake.gq', 'email-fake.ml',
  'email.cbes.net',
  'emailgo.de',
  'emailias.com',
  'emailinfive.com',
  'emaillime.com',
  'emailmiser.com',
  'emailn.de',
  'emailondeck.com',
  'emailrealtor.com',
  'emails.ga', 'emails.ml', 'emails.cf',
  'emailsensei.com',
  'emailtemporario.com.br',
  'emailtemp.org',
  'emailthe.net',
  'emailtmp.com',
  'emailto.de',
  'emailwarden.com',
  'emailx.at', 'emailx.net', 'emailx.org',
  'emailxfer.com',
  'emlhub.com', 'emlpro.com', 'emltmp.com',
  'enterto.com',
  'ephemail.net',
  'erightmail.com',
  'etranquil.com', 'etranquil.net', 'etranquil.org',
  'evopo.com',
  'exdonuts.com',
  'explodemail.com',
  'faaak.com',
  'fakemail.fr',
  'fakemail.ml', 'fakemail.ga', 'fakemail.cf',
  'fakemailgenerator.com',
  'fakemailz.com',
  'fammix.com',
  'fangoh.com',
  'fansworldwide.de',
  'fantasymail.de',
  'fastmail.ml', 'fastmail.ga', 'fastmail.cf',
  'fdfdsfds.com',
  'fightallspam.com',
  'filzmail.com',
  'fixmail.tk',
  'fivemail.ml',
  'flashbox.5july.org',
  'fmailbox.com',
  'fmguy.com',
  'fnzmail.com',
  'footard.com',
  'forgetmail.com',
  'fr33mail.info',
  'frapmail.com',
  'free-email.cf', 'free-email.ga',
  'freebabysittercam.com',
  'freecat.net',
  'freemail.casa',
  'freemail.ms',
  'freemails.cf',
  'freundin.ru',
  'friendlymail.co.uk',
  'fuckingduh.com',
  'fudgerub.com',
  'gafy.net',
  'garliclife.com',
  'gelitik.in',
  'get-mail.cf', 'get-mail.ga', 'get-mail.ml',
  'get1mail.com',
  'get2mail.com',
  'getairmail.com',
  'getmails.eu',
  'getnada.com', 'getnada.net',
  'gishpuppy.com',
  'glitch.sx',
  'globaleuro.net',
  'glubex.com',
  'glyqy.com',
  'goemailgo.com',
  'gomail.in',
  'goququ.com',
  'gotmail.org', 'gotmail.com',
  'grandmasmail.com',
  'greensloth.com',
  'grr.la',
  'gsrv.co.uk',
  'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.co.uk',
  'gustr.com',
  'h8s.org',
  'h9js.net',
  'haltospam.com',
  'harakirimail.com',
  'hartbot.de',
  'hashmail.ml',
  'headstrong.de',
  'heximail.com',
  'hidemail.de',
  'hidemail.pro', 'hidemail.us',
  'hiddentragedy.com',
  'hmamail.com',
  'hochsitze.com',
  'hopto.org',
  'hot-mail.cf', 'hot-mail.ga', 'hot-mail.gq', 'hot-mail.ml',
  'hotpop.com',
  'hstermail.com',
  'hurify.com',
  'i-phone.me',
  'ieatspam.eu', 'ieatspam.info',
  'ihateyoualot.info',
  'ihazspam.ca',
  'imails.info',
  'imgof.com',
  'inaby.com',
  'inbox.si',
  'inboxalias.com',
  'inboxbear.com',
  'inboxclean.com', 'inboxclean.org',
  'inboxhub.net',
  'inboxplace.com',
  'inboxstore.me',
  'inboxz.net',
  'incognitomail.com', 'incognitomail.net', 'incognitomail.org',
  'indieclad.com',
  'infocom.zp.ua',
  'inggo.org',
  'instant-mail.de',
  'instantemailaddress.com',
  'ip4.pp.ua',
  'ip6.pp.ua',
  'iqemail.com',
  'irish2mail.com',
  'iroid.com',
  'isdaq.com',
  'ivyro.net',
  'ixx.io',
  'jeie.igg.biz',
  'jmail.co.za',
  'jollyfree.com',
  'jourrapide.com',
  'jsrsolutions.com',
  'jumonji.tk',
  'jungkamushukum.com',
  'kaback.de',
  'kaffeeverkauf.com',
  'kaktusen.com',
  'kamsg.com',
  'kaspop.com',
  'keepmymail.com',
  'kennedy808.com',
  'killmail.com', 'killmail.net',
  'kimsdisk.com',
  'kkaku.com',
  'klassmaster.net',
  'klzlk.com',
  'kulturbetrieb.info',
  'kutakbis.cf',
  'l33r.eu',
  'labetteraverouge.at',
  'lackmail.net', 'lackmail.ru',
  'lagraz.com',
  'lakx.com',
  'landmail.co',
  'lastmail.co', 'lastmail.com',
  'lavabit.com',
  'lazyinbox.com', 'lazyinbox.us',
  'legitmail.club',
  'letmeinonthis.com',
  'letterboxes.org',
  'lexisense.com',
  'linuxfreemail.com',
  'litedrop.com',
  'livecareach.com',
  'llogin.net',
  'locanto1.club',
  'login-email.cf', 'login-email.ga', 'login-email.ml',
  'loin.in',
  'lol.com', 'lolfru.org',
  'lopl.co.cc',
  'lortemail.dk',
  'lovefall.ml',
  'lovemeet.faith',
  'lukso.net',
  'luky111.tk',
  'luv2.us',
  'm0y5yr9m.com',
  'macr2.com',
  'madcrave.com',
  'mail-filter.com',
  'mail-owl.com',
  'mail-temp.com',
  'mail.aik.lt',
  'mail.bccto.me',
  'mail.c', 'mail.cm',
  'mail.mezimages.net',
  'mail.mixhd.xyz',
  'mail.now.im',
  'mail.pandora.be',
  'mail.wtf',
  'mail0.0r0w.com',
  'mail1a.de',
  'mail2rss.org',
  'mail2world.com',
  'mail4trash.com',
  'mail4you.xyz',
  'mail666.ru',
  'mailabc.xyz',
  'mailbiz.biz',
  'mailbucket.org',
  'mailcat.biz',
  'mailcatch.com',
  'mailcker.com',
  'maildx.com',
  'maileater.com',
  'mailexpire.com',
  'mailfa.tk',
  'mailforspam.com',
  'mailfree.ga', 'mailfree.gq', 'mailfree.ml',
  'mailfs.com',
  'mailguard.me',
  'mailgutter.com',
  'mailhazard.com', 'mailhazard.us',
  'mailhex.com',
  'mailhub.pro',
  'mailimate.com',
  'mailinator.com', 'mailinator.net', 'mailinator.org',
  'mailinator2.com',
  'mailincubator.com',
  'mailismagic.com',
  'mailita.tk',
  'mailjunk.org',
  'mailmate.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailmoth.com',
  'mailnator.com',
  'mailnull.com',
  'mailonaut.com',
  'mailorc.com',
  'mailorg.org',
  'mailox.fun',
  'mailpick.biz',
  'mailpooch.com',
  'mailpost.ga',
  'mailproxsy.com',
  'mailquack.com',
  'mailr.de',
  'mailrocket.biz',
  'mailsac.com',
  'mailscrap.com',
  'mailseal.de',
  'mailshell.com',
  'mailshiv.com',
  'mailsiphon.com',
  'mailspam.xyz',
  'mailtemp.info',
  'mailtemporario.com.br',
  'mailtime.com',
  'mailtome.de',
  'mailtothis.com',
  'mailtraps.com',
  'mailtrash.net',
  'mailtrix.net',
  'mailtv.net', 'mailtv.tv',
  'mailunlimited.com',
  'mailup.net',
  'mailur.com',
  'mailuxe.com',
  'mailvidya.com',
  'mailwithyou.com',
  'mailz.info',
  'mailzer.net',
  'mailzilla.com', 'mailzilla.org',
  'makemenaughty.club',
  'malahov.de',
  'mansiondev.com',
  'manybrain.com',
  'mbt01.com',
  'mciek.com',
  'meantinc.com',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'messwiththebestdielikethe.rest',
  'metromin.com',
  'mhmm.cf',
  'midcoastcustoms.com',
  'midlertidig.com', 'midlertidig.net',
  'mijnhva.nl',
  'ministry-of-silly-walks.de',
  'mintl.xyz',
  'misterpinball.com',
  'mjukglass.nu',
  'moakt.com', 'moakt.ws',
  'mobileninja.co.uk',
  'monachat.tk',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monespace.fr.nf',
  'monmail.fr.nf',
  'monsieurfr.com',
  'monte-email.fr.nf',
  'moonwake.com',
  'moot.es',
  'moreawesomethanyou.com',
  'moreorcs.com',
  'mox.pp.ua',
  'ms9.mailslite.com',
  'mt2009.com',
  'mt2014.com',
  'mt2015.com',
  'mta2015.com',
  'mtmdev.com',
  'muathegame.com',
  'muchomail.com',
  'mucincanon.com',
  'my10minutemail.com',
  'my2mail.xyz',
  'myalias.pw',
  'mycleaninbox.net',
  'myemail.xyz',
  'myfreeblack.com',
  'myfreecams.com',
  'myindohome.services',
  'ymail.com',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'yuurok.com',
  'z1p.biz',
  'za.com',
  'zehnminutenmail.de',
  'zetmail.com',
  'zhcne.com',
  'zippymail.info',
  'zipsendtest.com',
  'zoaxe.com',
  'zoemail.org', 'zoemail.net', 'zoemail.com',
  'zomg.info',
  'zookeeper.email',
  'zxcv.com',
  'zxcvbnm.com',
  'zzz.com',
])

/**
 * Padrões suspeitos em emails
 */
const SUSPICIOUS_PATTERNS = [
  /^[a-f0-9]{8,}@/, // Hash-like local parts
  /^temp/i,
  /^fake/i,
  /^throw/i,
  /^dispose/i,
  /^trash/i,
  /\d{8,}@/, // Muitos números
  /^no-?reply/i,
  /^noreply/i,
  /^donotreply/i,
  /^mailer-daemon/i,
  /^postmaster/i,
]

/**
 * Verifica se um email é de domínio temporário conhecido
 */
export function isTempEmail(email: string): boolean {
  const normalized = email.trim().toLowerCase()
  const atIndex = normalized.lastIndexOf('@')
  if (atIndex === -1) return false

  const domain = normalized.slice(atIndex + 1)

  // Verificar domínio exato
  if (TEMP_EMAIL_DOMAINS.has(domain)) return true

  // Verificar subdomínios
  const parts = domain.split('.')
  for (let i = 1; i < parts.length - 1; i++) {
    const subDomain = parts.slice(i).join('.')
    if (TEMP_EMAIL_DOMAINS.has(subDomain)) return true
  }

  // Verificar padrões suspeitos no local part
  const localPart = normalized.slice(0, atIndex)
  for (const pattern of SUSPICIOUS_PATTERNS) {
    if (pattern.test(localPart)) return true
  }

  return false
}

/**
 * Verifica se o email tem formato válido
 */
export function isValidEmailFormat(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return emailRegex.test(email.trim())
}

/**
 * Valida email completo: formato + temporário
 */
export function validateEmail(email: string): {
  valid: boolean
  reason?: string
} {
  if (!email || !email.trim()) {
    return { valid: false, reason: 'Email é obrigatório' }
  }

  const normalized = email.trim().toLowerCase()

  if (!isValidEmailFormat(normalized)) {
    return { valid: false, reason: 'Formato de email inválido' }
  }

  if (normalized.length > 254) {
    return { valid: false, reason: 'Email muito longo' }
  }

  const localPart = normalized.slice(0, normalized.indexOf('@'))
  if (localPart.length > 64) {
    return { valid: false, reason: 'Nome do email muito longo' }
  }

  if (isTempEmail(normalized)) {
    return { valid: false, reason: 'Email temporário não é permitido' }
  }

  return { valid: true }
}

/**
 * Retorna lista completa de domínios bloqueados (para admin)
 */
export function getBlockedDomainsList(): string[] {
  return Array.from(TEMP_EMAIL_DOMAINS).sort()
}
