'use client'

import { motion } from 'framer-motion'
import Link from 'next/link'
import {
  MessageSquare, Image as ImageIcon, PenTool, LineChart, Radar, Shield,
  Search, Zap, ChevronRight, Sparkles, TrendingUp, Languages, Megaphone,
  BarChart3, MessageCircle, Bot, Heart, Flame, Type, Video, Mail, GitBranch,
  Calculator, Gift, BadgeCheck, Hash, MessageSquareText, ShieldOff, UserCircle,
  HelpCircle, Calendar, Users, Terminal, Target, Link as IconLink,
  LayoutTemplate, ListChecks, GitCompare, Instagram,
  ShieldCheck, UserX, ShoppingCart, Layers, Mic, Smile,
  Webhook, Lock, QrCode, Timer, BarChart4, MousePointerClick,
  Headphones, FileText, Receipt, Ticket, ShieldAlert, Radio, Network,
  Newspaper, AudioLines, BookHeart, FileEdit, FileBadge, ArrowDownToLine,
  Handshake, ScrollText, MessageCircleWarning, TrendingDown, Repeat, Coins,
  Landmark, Award, Presentation, Percent, ClipboardList, Receipt as ReceiptIcon,
  CheckSquare, PieChart, Film, HelpCircle as Question,
  Magnet, Clapperboard, MapPin, Palette, Camera, Banknote, Gem, RefreshCw,
  Rocket, Plug, Dices, Star,
} from 'lucide-react'

const AGENTS = [
  {
    id: 'support',
    nome: 'Kiya — Suporte 24h',
    tagline: 'Responde em segundos, 24h por dia',
    icone: MessageSquare,
    cor: 'from-emerald-500 to-teal-500',
    descricao: 'Atendimento ilimitado em português. Responde sobre entregas, pagamentos, reembolsos, como vender, afiliados.',
    ilimitado: true,
    href: '/suporte',
    cta: 'Falar com a Kiya', emBreve: false,
  },
  {
    id: 'bannerforge',
    nome: 'BannerForge',
    tagline: 'Banners e criativos SVG na hora',
    icone: ImageIcon,
    cor: 'from-pink-500 to-rose-500',
    descricao: 'Gera banners em 6 formatos (Hero, Quadrado, Story, Logo, Card, Anúncio) com gradientes e paleta de alta conversão.',
    ilimitado: false,
    href: '/agentes/bannerforge',
    cta: 'Gerar banner', emBreve: false,
  },
  {
    id: 'copywriter',
    nome: 'CopyMaster',
    tagline: 'Títulos e descrições que vendem',
    icone: PenTool,
    cor: 'from-amber-500 to-orange-500',
    descricao: '5 tons, 5 públicos, bullets, CTAs, hashtags e tags SEO otimizadas.',
    ilimitado: false,
    href: '/agentes/copymaster',
    cta: 'Escrever copy', emBreve: false,
  },
  {
    id: 'pricemaster',
    nome: 'PriceMaster',
    tagline: 'Preço ótimo com margem calculada',
    icone: LineChart,
    cor: 'from-blue-500 to-indigo-600',
    descricao: 'Preço ideal, margem líquida, preço psicológico e estratégia.',
    ilimitado: false,
    href: '/agentes/pricemaster',
    cta: 'Calcular preço', emBreve: false,
  },
  {
    id: 'producthunter',
    nome: 'ProductHunter',
    tagline: 'Descobre produtos lucrativos',
    icone: Radar,
    cor: 'from-violet-500 to-fuchsia-500',
    descricao: 'Catálogo curado de produtos com alta margem (+70%) e alta demanda no Brasil.',
    ilimitado: false,
    href: '/agentes/hunter',
    cta: 'Caçar produtos', emBreve: false,
  },
  {
    id: 'reviewshield',
    nome: 'ReviewShield',
    tagline: 'Moderação anti-fraude em tempo real',
    icone: Shield,
    cor: 'from-red-500 to-pink-600',
    descricao: 'Detecta contatos externos, spam CAIXA ALTA, frases genéricas de IA e tentativas de golpe.',
    ilimitado: true,
    href: '/agentes/reviewshield',
    cta: 'Verificar conteúdo', emBreve: false,
  },
  {
    id: 'freelancematch',
    nome: 'FreelanceMatch',
    tagline: 'Connecta você ao freela perfeito',
    icone: Bot,
    cor: 'from-cyan-500 to-sky-600',
    descricao: 'Sistema de propostas (bids) com escrow entre cliente e freelancer.',
    ilimitado: false,
    href: '/freelance',
    cta: 'Explorar freelas', emBreve: false,
  },
  {
    id: 'adoptimizer',
    nome: 'AdOptimizer',
    tagline: 'Turbo p/ anúncios Meta/TikTok',
    icone: TrendingUp,
    cor: 'from-yellow-400 to-orange-500',
    descricao: '5 variantes de copy, 3 públicos, orçamento ideal, CPA/ROAS estimado e dicas de thumbnail.',
    ilimitado: false,
    href: '/agentes/adoptimizer',
    cta: 'Otimizar anúncio', emBreve: false,
  },
  {
    id: 'replymaster',
    nome: 'ReplyMaster',
    tagline: 'Respostas automáticas de atendimento',
    icone: MessageCircle,
    cor: 'from-sky-500 to-indigo-500',
    descricao: 'Detecta sentimento e assunto do cliente, gera resposta com tom escolhido.',
    ilimitado: false,
    href: '/agentes/replymaster',
    cta: 'Gerar resposta', emBreve: false,
  },
  {
    id: 'seoboost',
    nome: 'SEOBoost',
    tagline: 'Meta tags e JSON-LD automáticos',
    icone: Search,
    cor: 'from-emerald-500 to-green-600',
    descricao: 'Meta title, description, OG, Twitter cards, slug, JSON-LD e palavras-chave.',
    ilimitado: false,
    href: '/agentes/seoboost',
    cta: 'Otimizar SEO', emBreve: false,
  },
  {
    id: 'seoscore',
    nome: 'SEOScore',
    tagline: 'Auditoria SEO 0-100',
    icone: BarChart3,
    cor: 'from-fuchsia-500 to-pink-600',
    descricao: 'Analisa título, descrição, imagens, bullets, emojis e tags com correções pontuais.',
    ilimitado: false,
    href: '/agentes/seoscore',
    cta: 'Auditar página', emBreve: false,
  },
  {
    id: 'translate',
    nome: 'KIYVO Translate',
    tagline: 'Traduza copy para EN/ES',
    icone: Languages,
    cor: 'from-teal-400 to-cyan-600',
    descricao: 'Traduza títulos, descrições e anúncios para inglês e espanhol.',
    ilimitado: false,
    href: '/agentes/translate',
    cta: 'Traduzir', emBreve: false,
  },
  {
    id: 'promogen',
    nome: 'PromoGen',
    tagline: 'Campanhas de desconto automáticas',
    icone: Megaphone,
    cor: 'from-rose-500 to-red-600',
    descricao: 'Nome de campanha, 5 variantes de desconto, cronograma de posts e cupom exclusivo.',
    ilimitado: false,
    href: '/agentes/promogen',
    cta: 'Criar promoção', emBreve: false,
  },
  {
    id: 'responder',
    nome: 'ReviewResponder',
    tagline: 'Responde TODAS avaliações auto',
    icone: MessageCircle,
    cor: 'from-sky-500 to-blue-600',
    descricao: 'Lê a avaliação, detecta sentimento e problema, escreve resposta profissional com tom à sua escolha.',
    ilimitado: false,
    href: '/agentes/responder',
    cta: 'Responder avaliação', emBreve: false,
  },
  {
    id: 'scarcity',
    nome: 'ScarcityForge',
    tagline: 'Gatilhos de urgência que convertem',
    icone: Flame,
    cor: 'from-red-500 to-orange-500',
    descricao: 'Badges de relâmpago, contadores, prova social e CTAs de oferta relâmpago em segundos.',
    ilimitado: false,
    href: '/agentes/scarcity',
    cta: 'Criar urgência', emBreve: false,
  },
  {
    id: 'titlesplit',
    nome: 'TitleSplit',
    tagline: '6 títulos com CTR estimado',
    icone: Type,
    cor: 'from-purple-500 to-indigo-600',
    descricao: 'Gera 6 variações de título usando fórmulas 4U, PAS, AIDA, Star-Story-Solution + CTR estimado.',
    ilimitado: false,
    href: '/agentes/titlesplit',
    cta: 'Split testar títulos', emBreve: false,
  },
  {
    id: 'scriptforge',
    nome: 'ScriptForge',
    tagline: 'Roteiros Reels/TikTok/VSL prontos',
    icone: Video,
    cor: 'from-pink-500 to-rose-600',
    descricao: 'Hook de 3s, cenas, CTA, hashtags, música sugerida e dicas de gravação.',
    ilimitado: false,
    href: '/agentes/scriptforge',
    cta: 'Gerar roteiro', emBreve: false,
  },
  {
    id: 'emailforge',
    nome: 'EmailForge',
    tagline: 'Sequências de e-mail completas',
    icone: Mail,
    cor: 'from-cyan-500 to-blue-600',
    descricao: 'Boas-vindas, carrinho abandonado, lançamento, pós-venda, reativação, BF — tudo pronto.',
    ilimitado: false,
    href: '/agentes/emailforge',
    cta: 'Gerar e-mails', emBreve: false,
  },
  {
    id: 'funnelforge',
    nome: 'FunnelForge',
    tagline: 'Funis de venda prontos em 1 clique',
    icone: GitBranch,
    cor: 'from-emerald-500 to-teal-600',
    descricao: 'Perpétuo, Oficina 24h, Tripwire, Lançamento Sniper, High Ticket, Afiliado ou Lead Ads.',
    ilimitado: false,
    href: '/agentes/funnelforge',
    cta: 'Criar funil', emBreve: false,
  },
  {
    id: 'descfetcher',
    nome: 'DescFetcher',
    tagline: 'Espia concorrente e cria versão 10x',
    icone: Search,
    cor: 'from-slate-700 to-slate-900',
    descricao: 'Cola a descrição do concorrente, a IA aponta fraquezas e gera uma descrição melhorada.',
    ilimitado: false,
    href: '/agentes/descfetcher',
    cta: 'Espiar concorrente', emBreve: false,
  },
  {
    id: 'taxcalc',
    nome: 'Calculadora de Lucro Real',
    tagline: 'Lucro LÍQUIDO sem surpresas',
    icone: Calculator,
    cor: 'from-green-500 to-emerald-600',
    descricao: 'Calcula taxas KIYVO + Stripe + IRPF/Simples + frete + anúncios. Preço de equilíbrio e ROAS mínimo.',
    ilimitado: true,
    href: '/agentes/taxcalc',
    cta: 'Calcular lucro', emBreve: false,
  },
  {
    id: 'competidor',
    nome: 'CompetidorRadar',
    tagline: 'Raio-X do mercado e nicho',
    icone: Radar,
    cor: 'from-violet-600 to-fuchsia-600',
    descricao: 'Saturação, preço ideal, concorrentes, canais, palavras-chave e plano de 30 dias.',
    ilimitado: false,
    href: '/agentes/competidor',
    cta: 'Analisar nicho', emBreve: false,
  },
  {
    id: 'bonusforge',
    nome: 'BonusForge',
    tagline: 'Pacotes de bônus irresistíveis',
    icone: Gift,
    cor: 'from-pink-500 to-purple-600',
    descricao: 'Gera checklist, swipe file, planilha, grupo VIP e bônus que triplicam o valor percebido.',
    ilimitado: false,
    href: '/agentes/bonusforge',
    cta: 'Criar bônus', emBreve: false,
  },
  {
    id: 'conquistas',
    nome: 'Conquistas KIYVO',
    tagline: 'Sistema de gamificação completo',
    icone: BadgeCheck,
    cor: 'from-amber-400 to-yellow-600',
    descricao: '20 badges, XP, níveis e KD Points por compra, venda, avaliação, afiliado e muito mais.',
    ilimitado: true,
    href: '/conquistas',
    cta: 'Ver conquistas', emBreve: false,
  },
  {
    id: 'hashtagger',
    nome: 'Hashtagger',
    tagline: 'Hashtags que viralizam',
    icone: Hash,
    cor: 'from-blue-500 to-cyan-500',
    descricao: 'Mistura hashtags grandes, médias e nichadas para Instagram/TikTok/YouTube — fórmula que funciona.',
    ilimitado: false,
    href: '/agentes/hashtagger',
    cta: 'Gerar hashtags', emBreve: false,
  },
  {
    id: 'captionforge',
    nome: 'CaptionForge',
    tagline: 'Legendas prontas p/ redes sociais',
    icone: MessageSquareText,
    cor: 'from-orange-500 to-red-500',
    descricao: 'Legendas para Instagram/TikTok/LinkedIn com hook, emojis, quebras de linha e CTA otimizado.',
    ilimitado: false,
    href: '/agentes/captionforge',
    cta: 'Gerar legenda', emBreve: false,
  },
  {
    id: 'objectiondestroyer',
    nome: 'ObjectionDestroyer',
    tagline: 'Respostas p/ todas objeções',
    icone: ShieldOff,
    cor: 'from-red-500 to-pink-600',
    descricao: 'Respostas prontas para "está caro", "vou pensar", "tenho medo de golpe" e outras 10 objeções.',
    ilimitado: false,
    href: '/agentes/objectiondestroyer',
    cta: 'Ver respostas', emBreve: false,
  },
  {
    id: 'biogenerator',
    nome: 'BioGenerator',
    tagline: 'Bio pronta para todas redes',
    icone: UserCircle,
    cor: 'from-fuchsia-500 to-pink-600',
    descricao: 'Bios otimizadas para Instagram/TikTok/YouTube/LinkedIn/X + sugestões de username.',
    ilimitado: false,
    href: '/agentes/biogenerator',
    cta: 'Gerar bio', emBreve: false,
  },
  {
    id: 'faqmaker',
    nome: 'FAQMaker',
    tagline: 'FAQ com JSON-LD para SEO',
    icone: HelpCircle,
    cor: 'from-teal-500 to-cyan-600',
    descricao: '12 perguntas e respostas + JSON-LD estruturado que aumenta tráfego orgânico em 20%+.',
    ilimitado: false,
    href: '/agentes/faqmaker',
    cta: 'Gerar FAQ', emBreve: false,
  },
  {
    id: 'contentcalendar',
    nome: 'ContentCalendar',
    tagline: 'Calendário editorial de 30 dias',
    icone: Calendar,
    cor: 'from-indigo-500 to-purple-600',
    descricao: 'Plano diário de reels, posts, stories e lives com temas, hooks e CTAs prontos.',
    ilimitado: false,
    href: '/agentes/contentcalendar',
    cta: 'Gerar calendário', emBreve: false,
  },
  {
    id: 'seooptimizer',
    nome: 'SEOOptimizer',
    tagline: 'Meta tags, slug e JSON-LD',
    icone: Search,
    cor: 'from-emerald-500 to-green-600',
    descricao: 'Gera meta title, description, OG, Twitter, slug e JSON-LD completos em segundos.',
    ilimitado: false,
    href: '/agentes/seooptimizer',
    cta: 'Otimizar SEO', emBreve: false,
  },
  {
    id: 'trafficoptimizer',
    nome: 'TrafficOptimizer',
    tagline: 'Distribui orçamento entre canais',
    icone: BarChart3,
    cor: 'from-yellow-500 to-orange-600',
    descricao: 'Calcula distribuição ideal de orçamento entre Meta, TikTok, Google, YouTube e remarketing.',
    ilimitado: false,
    href: '/agentes/trafficoptimizer',
    cta: 'Otimizar tráfego', emBreve: false,
  },
  {
    id: 'personabuilder',
    nome: 'PersonaBuilder',
    tagline: 'Personas completas de cliente',
    icone: Users,
    cor: 'from-pink-500 to-rose-600',
    descricao: 'Cria personas com nome, idade, frustrações, desejos, objeções e estratégia de funil.',
    ilimitado: false,
    href: '/agentes/personabuilder',
    cta: 'Criar persona', emBreve: false,
  },
  {
    id: 'nameforge',
    nome: 'NameForge',
    tagline: 'Nomes de marca com slogan',
    icone: Sparkles,
    cor: 'from-purple-500 to-pink-600',
    descricao: 'Gera nomes de produtos/marcas em 6 estilos (moderno, premium, tech, BR) + domínio e @.',
    ilimitado: false,
    href: '/agentes/nameforge',
    cta: 'Gerar nomes', emBreve: false,
  },
  {
    id: 'promptengineer',
    nome: 'PromptEngineer',
    tagline: 'Prompts profissionais p/ IA',
    icone: Terminal,
    cor: 'from-slate-700 to-black',
    descricao: 'Prompts estruturados para ChatGPT, Gemini, Claude, Midjourney e DALL-E com system prompt.',
    ilimitado: true,
    href: '/agentes/promptengineer',
    cta: 'Criar prompt', emBreve: false,
  },
  {
    id: 'whatsappforge',
    nome: 'WhatsAppForge',
    tagline: 'Sequências WhatsApp que vendem',
    icone: MessageCircle,
    cor: 'from-green-500 to-emerald-600',
    descricao: 'Mensagens com delays naturais para vendas, follow-up, boas-vindas, carrinho abandonado.',
    ilimitado: false,
    href: '/agentes/whatsappforge',
    cta: 'Gerar mensagens', emBreve: false,
  },
  {
    id: 'storybuilder',
    nome: 'StoryBuilder',
    tagline: 'Stories com enquete/quiz/CTA',
    icone: Instagram,
    cor: 'from-pink-500 via-red-500 to-yellow-500',
    descricao: 'Sequências de stories com enquetes, quizzes, emojis e CTAs que aumentam alcance.',
    ilimitado: false,
    href: '/agentes/storybuilder',
    cta: 'Criar stories', emBreve: false,
  },
  {
    id: 'pixelperfect',
    nome: 'PixelPerfect',
    tagline: 'Diagnóstico de pixel/tracking',
    icone: Target,
    cor: 'from-red-500 to-orange-600',
    descricao: 'Checklist de eventos Meta/Google/TikTok, CAPI e otimização para aumentar ROAS.',
    ilimitado: true,
    href: '/agentes/pixelperfect',
    cta: 'Diagnosticar pixel', emBreve: false,
  },
  {
    id: 'urltracker',
    nome: 'URLTracker',
    tagline: 'Links com UTM automáticos',
    icone: IconLink,
    cor: 'from-cyan-500 to-blue-600',
    descricao: 'Gera links rastreados com UTM para cada plataforma (Meta, Google, TikTok, afiliados).',
    ilimitado: true,
    href: '/agentes/urltracker',
    cta: 'Gerar UTM', emBreve: false,
  },
  {
    id: 'landingforge',
    nome: 'LandingForge',
    tagline: 'Estrutura de landing page',
    icone: LayoutTemplate,
    cor: 'from-indigo-500 to-blue-700',
    descricao: 'Seções de uma landing de alta conversão: hero, dor, solução, prova, oferta, garantia, FAQ.',
    ilimitado: false,
    href: '/agentes/landingforge',
    cta: 'Gerar landing', emBreve: false,
  },
  {
    id: 'bulletforge',
    nome: 'BulletForge',
    tagline: 'Bullets de fascinação',
    icone: ListChecks,
    cor: 'from-red-500 to-rose-600',
    descricao: 'Bullets matadores em 6 estilos (curiosidade, segredo, mecanismo, ameaça, resultado, prova).',
    ilimitado: false,
    href: '/agentes/bulletforge',
    cta: 'Forjar bullets', emBreve: false,
  },
  {
    id: 'abtester',
    nome: 'ABTester',
    tagline: 'Calculadora de teste A/B',
    icone: GitCompare,
    cor: 'from-cyan-500 to-teal-600',
    descricao: 'Significância estatística, intervalo de confiança e recomendação de vencedor.',
    ilimitado: true,
    href: '/agentes/abtester',
    cta: 'Calcular teste', emBreve: false,
  },
  // v8.9 NEO EVOLUTION — 22 novos agentes
  {
    id: 'automod',
    nome: 'AutoMod',
    tagline: 'Moderação automática em tempo real',
    icone: ShieldCheck,
    cor: 'from-red-500 to-rose-600',
    descricao: 'Bloqueia spam, contatos externos, ameaças e pagamentos fora da plataforma automaticamente.',
    ilimitado: true,
    href: '/agentes/automod',
    cta: 'Moderar texto', emBreve: false,
  },
  {
    id: 'dynamicpricing',
    nome: 'DynamicPricing',
    tagline: 'Preço dinâmico baseado em dados',
    icone: LineChart,
    cor: 'from-blue-500 to-indigo-600',
    descricao: 'Ajusta preço automaticamente com base em estoque, demanda, horário, concorrência e nota.',
    ilimitado: false,
    href: '/agentes/dynamicpricing',
    cta: 'Calcular preço dinâmico', emBreve: false,
  },
  {
    id: 'churnpredictor',
    nome: 'ChurnPredictor',
    tagline: 'Preveja quem vai deixar a plataforma',
    icone: UserX,
    cor: 'from-orange-500 to-red-600',
    descricao: 'Score de risco de evasão com ofertas de retenção personalizadas (cupons + KD Points).',
    ilimitado: true,
    href: '/agentes/churnpredictor',
    cta: 'Analisar retenção', emBreve: false,
  },
  {
    id: 'smartcart',
    nome: 'SmartCart',
    tagline: 'Carrinho inteligente com upsell automático',
    icone: ShoppingCart,
    cor: 'from-emerald-500 to-teal-600',
    descricao: 'Calcula descontos de combo, KD Points, sugere upsell/cross-sell/bundle em tempo real.',
    ilimitado: true,
    href: '/agentes/smartcart',
    cta: 'Analisar carrinho', emBreve: false,
  },
  {
    id: 'retargetpredictor',
    nome: 'RetargetPredictor',
    tagline: 'Quem precisa de retargeting? Quando? Oferta?',
    icone: Target,
    cor: 'from-cyan-500 to-blue-600',
    descricao: 'Identifica leads quentes/frios e sugere canal ideal (email/whats/push) + oferta ideal.',
    ilimitado: true,
    href: '/agentes/retargetpredictor',
    cta: 'Gerar campanhas', emBreve: false,
  },
  {
    id: 'titlescorer',
    nome: 'TitleScorer',
    tagline: 'Nota 0-100 para seus títulos',
    icone: Type,
    cor: 'from-violet-500 to-fuchsia-500',
    descricao: 'Pontua títulos por checklist (tamanho, power words, números, spam) e gera variantes.',
    ilimitado: false,
    href: '/agentes/titlescorer',
    cta: 'Pontuar título', emBreve: false,
  },
  {
    id: 'thumbnailmaker',
    nome: 'ThumbnailMaker',
    tagline: 'Thumbnails SVG prontos para YouTube/TikTok',
    icone: ImageIcon,
    cor: 'from-pink-500 to-rose-600',
    descricao: 'Gera thumbnails em SVG com paleta do nicho + dicas de CTR e composição.',
    ilimitado: false,
    href: '/agentes/thumbnailmaker',
    cta: 'Gerar thumbnail', emBreve: false,
  },
  {
    id: 'scriptshort',
    nome: 'ScriptShort',
    tagline: 'Roteiros para TikTok/Reels/Shorts',
    icone: Video,
    cor: 'from-fuchsia-500 to-purple-600',
    descricao: 'Roteiros de 15s/30s/60s com hook, cenas, texto de tela, CTA e hashtags.',
    ilimitado: false,
    href: '/agentes/scriptshort',
    cta: 'Gerar roteiro curto', emBreve: false,
  },
  {
    id: 'offerstacker',
    nome: 'OfferStacker',
    tagline: 'Stack completa de ofertas (tripwire → high-ticket)',
    icone: Layers,
    cor: 'from-amber-500 to-orange-600',
    descricao: 'Monta lead magnet → front-end → bump → upsell 1 → upsell 2 → downsell com scripts.',
    ilimitado: false,
    href: '/agentes/offerstacker',
    cta: 'Montar stack', emBreve: false,
  },
  {
    id: 'voiceclonepreview',
    nome: 'VoicePrep',
    tagline: 'Preparação de roteiro para narração',
    icone: Mic,
    cor: 'from-teal-500 to-emerald-600',
    descricao: 'Segmenta texto em falas/pausas/ênfases com tom ideal e velocidade por cenário.',
    ilimitado: false,
    href: '/agentes/voiceclonepreview',
    cta: 'Preparar roteiro', emBreve: false,
  },
  {
    id: 'landingchecker',
    nome: 'LandingChecker',
    tagline: 'Nota A+ a E da sua landing page',
    icone: LayoutTemplate,
    cor: 'from-indigo-500 to-blue-600',
    descricao: 'Audita hero, CTA, prova social, garantia, FAQ, urgência e sugere correções pontuais.',
    ilimitado: true,
    href: '/agentes/landingchecker',
    cta: 'Auditar landing', emBreve: false,
  },
  {
    id: 'reviewreplier',
    nome: 'ReviewReplier',
    tagline: 'Responde reviews de 1★ a 5★',
    icone: MessageSquareText,
    cor: 'from-sky-500 to-blue-600',
    descricao: 'Respostas empáticas para avaliações positivas e negativas com pedido de reavaliação.',
    ilimitado: false,
    href: '/agentes/reviewreplier',
    cta: 'Gerar resposta', emBreve: false,
  },
  {
    id: 'competitormonitor',
    nome: 'CompetitorMonitor',
    tagline: 'Monitora preços e força de concorrentes',
    icone: Radar,
    cor: 'from-violet-500 to-purple-600',
    descricao: 'Raio-X de concorrência com SWOT, comparação de preços e gaps de oportunidade.',
    ilimitado: false,
    href: '/agentes/competitormonitor',
    cta: 'Analisar concorrentes', emBreve: false,
  },
  {
    id: 'socialproofengine',
    nome: 'SocialProofEngine',
    tagline: 'Notificações de compra social em tempo real',
    icone: Users,
    cor: 'from-pink-500 to-rose-600',
    descricao: 'Mensagens tipo "fulano de SP comprou há 2 minutos" para aumentar conversão em até 15%.',
    ilimitado: true,
    href: '/agentes/socialproofengine',
    cta: 'Gerar prova social', emBreve: false,
  },
  {
    id: 'quizfunnel',
    nome: 'QuizFunnel',
    tagline: 'Funis de quiz para segmentar e vender',
    icone: HelpCircle,
    cor: 'from-emerald-500 to-green-600',
    descricao: 'Quiz de 3-8 perguntas com segmentação automática e oferta personalizada no final.',
    ilimitado: false,
    href: '/agentes/quizfunnel',
    cta: 'Criar quiz', emBreve: false,
  },
  {
    id: 'seobriefing',
    nome: 'SEOBriefing',
    tagline: 'Briefing completo de SEO em 1 clique',
    icone: Search,
    cor: 'from-green-500 to-emerald-600',
    descricao: 'Título, meta, slug, headings, perguntas, tamanho ideal, schema JSON-LD e links internos.',
    ilimitado: true,
    href: '/agentes/seobriefing',
    cta: 'Gerar briefing SEO', emBreve: false,
  },
  {
    id: 'contentauditor',
    nome: 'ContentAuditor',
    tagline: 'Auditor LGPD/CDC/SEO automática',
    icone: ShieldCheck,
    cor: 'from-slate-700 to-slate-900',
    descricao: 'Detecta promessas ilegais, garante conformidade legal e previne bloqueios de anúncios.',
    ilimitado: true,
    href: '/agentes/contentauditor',
    cta: 'Auditar conteúdo', emBreve: false,
  },
  {
    id: 'emojipicker',
    nome: 'EmojiPicker',
    tagline: 'Emojis relevantes por contexto',
    icone: Smile,
    cor: 'from-yellow-400 to-orange-500',
    descricao: 'Seleciona emojis por nicho, formata bullets e posiciona no início/meio/fim.',
    ilimitado: true,
    href: '/agentes/emojipicker',
    cta: 'Escolher emojis', emBreve: false,
  },
  {
    id: 'launchchecklist',
    nome: 'LaunchChecklist',
    tagline: 'Checklist COMPLETO do D-14 ao D+7',
    icone: ListChecks,
    cor: 'from-blue-500 to-cyan-600',
    descricao: 'Todas tarefas, obrigatórias ou opcionais, para lançar produto digital sem esquecer nada.',
    ilimitado: true,
    href: '/agentes/launchchecklist',
    cta: 'Gerar checklist', emBreve: false,
  },
  {
    id: 'personacraft',
    nome: 'PersonaCraft',
    tagline: 'Personas completas e anti-personas',
    icone: UserCircle,
    cor: 'from-fuchsia-500 to-pink-600',
    descricao: 'Perfis detalhados com nome, cidade, dores, desejos, objeções, frase representativa e oferta ideal.',
    ilimitado: false,
    href: '/agentes/personacraft',
    cta: 'Criar personas', emBreve: false,
  },
  {
    id: 'urgenciamaker',
    nome: 'UrgenciaMaker',
    tagline: 'Escassez honesta (estoque, tempo, vagas)',
    icone: Flame,
    cor: 'from-red-500 to-orange-500',
    descricao: 'Linhas de urgência honestas para estoque, vagas e promoções com dicas de ética.',
    ilimitado: true,
    href: '/agentes/urgenciamaker',
    cta: 'Criar urgência', emBreve: false,
  },
  {
    id: 'metricsanalyzer',
    nome: 'MetricsAnalyzer',
    tagline: 'Diagnóstico de métricas com ações',
    icone: BarChart3,
    cor: 'from-indigo-500 to-purple-600',
    descricao: 'Analisa tráfego → cart → checkout → compra → reembolso e diz exatamente o que corrigir.',
    ilimitado: true,
    href: '/agentes/metricsanalyzer',
    cta: 'Analisar métricas', emBreve: false,
  },
  {
    id: 'webhooktester',
    nome: 'WebhookTester',
    tagline: 'Payloads prontos para testar webhooks',
    icone: Webhook,
    cor: 'from-slate-600 to-slate-800',
    descricao: 'Gera payloads reais de compra/PIX/reembolso + comando curl para teste imediato.',
    ilimitado: true,
    href: '/agentes/webhooktester',
    cta: 'Testar webhooks', emBreve: false,
  },
  {
    id: 'qrcodegen',
    nome: 'QRGenerator',
    tagline: 'QR Codes estilizados com logo KIYVO',
    icone: QrCode,
    cor: 'from-slate-700 to-black',
    descricao: 'Gera QR Codes SVG para PIX, links, WhatsApp, produtos com K no centro.',
    ilimitado: true,
    href: '/agentes/qrcodegen',
    cta: 'Gerar QR Code', emBreve: false,
  },
  {
    id: 'senhaforge',
    nome: 'SenhaForge',
    tagline: 'Gerador de senhas ultra-seguras',
    icone: Lock,
    cor: 'from-slate-700 to-black',
    descricao: 'Senhas com entropia real, força visual e tempo estimado de quebra.',
    ilimitado: true,
    href: '/agentes/senhaforge',
    cta: 'Gerar senha', emBreve: false,
  },
  {
    id: 'validatorbr',
    nome: 'ValidatorBR',
    tagline: 'Valida CPF/CNPJ/CEP/PIX/Cartão/Email/Telefone',
    icone: ShieldCheck,
    cor: 'from-emerald-500 to-green-600',
    descricao: 'Validação brasileira oficial de documentos e dados com formatação automática.',
    ilimitado: true,
    href: '/agentes/validatorbr',
    cta: 'Validar documento', emBreve: false,
  },
  {
    id: 'contadorregressivo',
    nome: 'ContadorRegressivo',
    tagline: 'Contadores prontos para ofertas e lançamentos',
    icone: Timer,
    cor: 'from-red-500 to-orange-500',
    descricao: 'Gera HTML e Tailwind de countdown com frases de urgência.',
    ilimitado: true,
    href: '/agentes/contadorregressivo',
    cta: 'Criar contador', emBreve: false,
  },
  {
    id: 'gradehorarios',
    nome: 'GradeHorários',
    tagline: 'Grade semanal de conteúdo com horários',
    icone: Calendar,
    cor: 'from-indigo-500 to-violet-600',
    descricao: 'Plano de postagem diária com tarefas, duração, categorias e ferramentas.',
    ilimitado: false,
    href: '/agentes/gradehorarios',
    cta: 'Gerar grade', emBreve: false,
  },
  {
    id: 'ctamaker',
    nome: 'CTAMaker',
    tagline: 'Botões de call-to-action em 5 tons',
    icone: MousePointerClick,
    cor: 'from-amber-500 to-orange-600',
    descricao: 'CTAs persuasivos em tom direto, curioso, benefício, urgência ou humilde.',
    ilimitado: true,
    href: '/agentes/ctamaker',
    cta: 'Gerar CTAs', emBreve: false,
  },
  {
    id: 'npsanalyzer',
    nome: 'NPSAnalyzer',
    tagline: 'Calcula NPS e sugere ações por segmento',
    icone: BarChart4,
    cor: 'from-emerald-500 to-teal-600',
    descricao: 'Insira quantidade de promotores, neutros e detratores e receba diagnóstico completo.',
    ilimitado: true,
    href: '/agentes/npsanalyzer',
    cta: 'Calcular NPS', emBreve: false,
  },
  {
    id: 'slugmaker',
    nome: 'SlugMaker',
    tagline: 'URLs/slugs SEO-friendly automaticamente',
    icone: IconLink,
    cor: 'from-cyan-500 to-blue-600',
    descricao: 'Remove acentos, gera alternativas e cria URLs permanentes com ID curto.',
    ilimitado: true,
    href: '/agentes/slugmaker',
    cta: 'Gerar slug', emBreve: false,
  },
  { id: 'headlineanalyzer', nome: 'HeadlineAnalyzer', tagline: '10 fórmulas clássicas de headline que vendem', icone: Type, cor: 'from-red-500 to-rose-600', descricao: 'Gera títulos com fórmulas comprovadas: Como, Erros, Verdade, Antes/depois, PAS.', ilimitado: false, href: '/agentes/headlineanalyzer', cta: 'Gerar headlines', emBreve: false },
  { id: 'emailsequencia', nome: 'EmailSequencia', tagline: 'Sequência de emails de 7 dias pronta', icone: Mail, cor: 'from-cyan-500 to-blue-600', descricao: 'Boas-vindas, warmup, problema, prova, social, fechamento e last-call.', ilimitado: false, href: '/agentes/emailsequencia', cta: 'Gerar emails', emBreve: false },
  { id: 'blogideia', nome: 'BlogIdeia', tagline: '15+ ideias de posts de blog por nicho', icone: Newspaper, cor: 'from-indigo-500 to-violet-600', descricao: 'Ideias com ângulos, tipo de post, palavras-chave e duração de leitura.', ilimitado: true, href: '/agentes/blogideia', cta: 'Gerar ideias', emBreve: false },
  { id: 'problemaagitacao', nome: 'PAS Copy', tagline: 'Copy usando Problema-Agitação-Solução', icone: Flame, cor: 'from-red-500 to-orange-500', descricao: 'Estrutura clássica de copywriting: mostra a dor, agrava, apresenta saída.', ilimitado: false, href: '/agentes/problemaagitacao', cta: 'Gerar copy PAS', emBreve: false },
  { id: 'podcastscript', nome: 'PodcastScript', tagline: 'Pauta completa de podcast/entrevista', icone: AudioLines, cor: 'from-purple-500 to-pink-600', descricao: 'Blocos, perguntas, warm-up, rápido e CTA final com tempos definidos.', ilimitado: false, href: '/agentes/podcastscript', cta: 'Gerar pauta', emBreve: false },
  { id: 'faturaprojecao', nome: 'FaturaProjeção', tagline: 'Projeta faturamento do funil em cenários', icone: BarChart3, cor: 'from-emerald-500 to-green-600', descricao: 'Pior, esperado e melhor cenário com ROAS e lucro líquido estimado.', ilimitado: true, href: '/agentes/faturaprojecao', cta: 'Projetar receita', emBreve: false },
  { id: 'whatsappboasvindas', nome: 'WhatsApp Boas-Vindas', tagline: 'Fluxo de boas-vindas para WhatsApp/IG', icone: MessageCircle, cor: 'from-green-500 to-emerald-600', descricao: 'Mensagens com delays naturais para onboarding no WhatsApp.', ilimitado: false, href: '/agentes/whatsappboasvindas', cta: 'Gerar fluxo', emBreve: false },
  { id: 'invoicegen', nome: 'InvoiceGen', tagline: 'Recibos/NF em HTML prontos para imprimir', icone: Receipt, cor: 'from-slate-600 to-slate-900', descricao: 'Recibo profissional com dados de emissor, cliente, itens e total.', ilimitado: true, href: '/agentes/invoicegen', cta: 'Gerar recibo', emBreve: false },
  { id: 'testimonialcrafter', nome: 'TestimonialCrafter', tagline: 'Depoimentos de exemplo para layout', icone: BookHeart, cor: 'from-rose-500 to-pink-600', descricao: 'Cria exemplos de depoimentos — NUNCA invente depoimentos reais.', ilimitado: true, href: '/agentes/testimonialcrafter', cta: 'Ver exemplos', emBreve: false },
  { id: 'plrsearch', nome: 'PLRSearch', tagline: 'Ideias de produtos PLR por nicho', icone: FileText, cor: 'from-amber-500 to-orange-600', descricao: 'Sugere ebooks, checklists, templates PLR com preço sugerido.', ilimitado: false, href: '/agentes/plrsearch', cta: 'Explorar PLR', emBreve: false },
  { id: 'warmup', nome: 'WarmupPlan', tagline: 'Plano de aquecimento de domínio email', icone: ArrowDownToLine, cor: 'from-teal-500 to-emerald-600', descricao: 'Plano 14 dias de envio gradual com lista, volumes e assuntos.', ilimitado: true, href: '/agentes/warmup', cta: 'Gerar plano', emBreve: false },
  { id: 'affiliateproposal', nome: 'AffiliateProposal', tagline: 'Proposta de afiliado para criadores', icone: Handshake, cor: 'from-violet-500 to-purple-700', descricao: 'DM curta, proposta completa e email de convite para parceiros.', ilimitado: false, href: '/agentes/affiliateproposal', cta: 'Gerar proposta', emBreve: false },
  { id: 'faqauto', nome: 'FAQAuto', tagline: 'FAQ automática com objeções comuns', icone: HelpCircle, cor: 'from-teal-500 to-cyan-600', descricao: '8+ perguntas e respostas prontas com base no nicho/produto.', ilimitado: true, href: '/agentes/faqauto', cta: 'Gerar FAQ', emBreve: false },
  { id: 'referralbadge', nome: 'ReferralBadge', tagline: 'Selo SVG de indicação personalizado', icone: FileBadge, cor: 'from-blue-500 to-indigo-600', descricao: 'Selo "Eu recomendo" com seu nome, código e cor.', ilimitado: true, href: '/agentes/referralbadge', cta: 'Gerar selo', emBreve: false },
  { id: 'riskscore', nome: 'RiskScore', tagline: 'Score antifraude em tempo real', icone: ShieldAlert, cor: 'from-red-600 to-rose-700', descricao: 'Calcula risco de fraude por IP, email, dispositivo, valor e comportamento.', ilimitado: true, href: '/agentes/riskscore', cta: 'Calcular risco', emBreve: false },
  { id: 'feedbackinterpreter', nome: 'FeedbackInterpreter', tagline: 'Interpreta feedbacks (sentimento + categoria)', icone: MessageCircleWarning, cor: 'from-orange-500 to-red-600', descricao: 'Lê texto e nota, classifica em problema técnico/cobrança/entrega/suporte.', ilimitado: true, href: '/agentes/feedbackinterpreter', cta: 'Interpretar', emBreve: false },
  { id: 'valedecesconto', nome: 'CupomMaker', tagline: 'Gera códigos de cupom criativos', icone: Ticket, cor: 'from-pink-500 to-rose-600', descricao: 'Cupons de boas-vindas, lançamento, parceiro, recuperação, BF.', ilimitado: true, href: '/agentes/valedecesconto', cta: 'Gerar cupom', emBreve: false },
  { id: 'contratorapido', nome: 'ContratoRápido', tagline: 'Minutas básicas (freelance/afiliado/parceria)', icone: ScrollText, cor: 'from-slate-700 to-slate-900', descricao: 'Pontos chave — validar com advogado antes de assinar.', ilimitado: false, href: '/agentes/contratorapido', cta: 'Gerar minuta', emBreve: false },
  // v9.2 Monetização
  { id: 'custosreais', nome: 'Custos Reais de Venda', tagline: 'Gateway+plataforma+impostos abertos', icone: ReceiptIcon, cor: 'from-slate-600 to-slate-900', descricao: 'Detalha todos os custos: Stripe/PIX/KIYVO, comissões, CAC. Lucro real.', ilimitado: false, href: '/agentes/custosreais', cta: 'Calcular custos', emBreve: false },
  { id: 'bumpcriador', nome: 'Criador de Order Bump', tagline: 'Bump que converte 25-40%', icone: CheckSquare, cor: 'from-amber-500 to-orange-600', descricao: 'Cria o bump de checkout perfeito (15-30% do valor principal).', ilimitado: false, href: '/agentes/bumpcriador', cta: 'Criar bump', emBreve: false },
  { id: 'otosequencia', nome: 'Sequência de OTO', tagline: 'Bump+OTO+Downsell+Assinatura', icone: Repeat, cor: 'from-pink-500 to-purple-600', descricao: 'Funil completo de upsell de 1 clique que pode dobrar o ticket.', ilimitado: false, href: '/agentes/otosequencia', cta: 'Gerar funil OTO', emBreve: false },
  { id: 'scriptspn', nome: 'Script SPN', tagline: 'Sofrimento→Ponte→Nova Vida', icone: Flame, cor: 'from-violet-500 to-indigo-700', descricao: 'Estrutura clássica de vendas para vídeos e textos.', ilimitado: false, href: '/agentes/scriptspn', cta: 'Gerar script', emBreve: false },
  { id: 'refunddesescalador', nome: 'Desescalador Refund', tagline: 'Reduz reembolso sem negar devolução', icone: Handshake, cor: 'from-emerald-500 to-green-700', descricao: 'Mensagens que acalmam e retêm cliente pedindo refund.', ilimitado: false, href: '/agentes/refunddesescalador', cta: 'Ver mensagens', emBreve: false },
  { id: 'profitfirst', nome: 'Profit First', tagline: '50/30/10/10 adaptado ao Brasil', icone: Landmark, cor: 'from-green-500 to-teal-700', descricao: 'Simula a regra do lucro primeiro: separar lucro antes de gastar.', ilimitado: false, href: '/agentes/profitfirst', cta: 'Simular lucro', emBreve: false },
  { id: 'giftcardcriador', nome: 'Criador Gift Card', tagline: 'Vale-presente promocional', icone: Gift, cor: 'from-pink-500 to-rose-600', descricao: 'Gera código e valor com bônus percentual automático.', ilimitado: false, href: '/agentes/giftcardcriador', cta: 'Criar gift card', emBreve: false },
  { id: 'cashbackcalc', nome: 'Cashback KD', tagline: 'Calcula pontos de cashback', icone: Coins, cor: 'from-yellow-400 to-amber-600', descricao: 'Quantos KD Points o comprador ganha por compra.', ilimitado: true, href: '/agentes/cashbackcalc', cta: 'Calcular cashback', emBreve: false },
  { id: 'leadmagnetpro', nome: 'Lead Magnet Pro', tagline: '7 ideias de isca com % de conversão', icone: Zap, cor: 'from-cyan-500 to-blue-700', descricao: 'Checklists, planilhas, quiz, calculadora, mini-curso com conversão estimada.', ilimitado: false, href: '/agentes/leadmagnetpro', cta: 'Ver ideias', emBreve: false },
  { id: 'aumentarticket', nome: 'Aumentar Ticket Médio', tagline: '10 estratégias de AOV', icone: TrendingUp, cor: 'from-indigo-500 to-blue-700', descricao: 'Bump, upsell, bundles, cross-sell, assinatura — estratégias práticas.', ilimitado: true, href: '/agentes/aumentarticket', cta: 'Ver estratégias', emBreve: false },
  { id: 'webinarroteiro', nome: 'Roteiro de Webinar', tagline: 'Webinar de 90min que converte 8-15%', icone: Presentation, cor: 'from-red-500 to-rose-700', descricao: 'Minuto a minuto: abertura, dor, valor, virada, oferta, fechamento.', ilimitado: false, href: '/agentes/webinarroteiro', cta: 'Gerar roteiro', emBreve: false },
  { id: 'perguntasfechamento', nome: '12 Perguntas que Fecham', tagline: 'Perguntas que levam ao SIM', icone: Question, cor: 'from-fuchsia-500 to-pink-700', descricao: 'Perguntas de fechamento mais poderosas que afirmações.', ilimitado: true, href: '/agentes/perguntasfechamento', cta: 'Ver perguntas', emBreve: false },
  // v9.0 - Monetização e Vendas
  { id: 'lucromax', nome: 'LucroMax', tagline: 'Calculadora lucro real com taxas', icone: Calculator, cor: 'from-green-600 to-emerald-800', descricao: 'Calcula lucro líquido após KIYVO, afiliado, impostos, custos.', ilimitado: true, href: '/agentes/lucromax', cta: 'Calcular lucro', emBreve: false },
  { id: 'upsellmax', nome: 'UpsellMax', tagline: 'Ofertas upsell/downsell irresistíveis', icone: TrendingUp, cor: 'from-orange-600 to-red-600', descricao: 'Cria OTO, order bump, downsell e cross-sell.', ilimitado: false, href: '/agentes/upsellmax', cta: 'Criar upsell', emBreve: false },
  { id: 'carrinhoabandonado', nome: 'Carrinho Abandonado', tagline: 'Sequência de recuperação de venda', icone: ShoppingCart, cor: 'from-amber-600 to-orange-700', descricao: '4 mensagens de recuperação de carrinho com cupom.', ilimitado: false, href: '/agentes/carrinhoabandonado', cta: 'Recuperar vendas', emBreve: false },
  { id: 'precificacaointeligente', nome: 'Precificação Inteligente', tagline: 'Preços psicológicos que vendem', icone: Percent, cor: 'from-purple-600 to-indigo-700', descricao: 'Preços 47/97/147/197, preço-âncora, preço mínimo.', ilimitado: false, href: '/agentes/precificacaointeligente', cta: 'Precificar', emBreve: false },
  { id: 'garantia', nome: 'Garantia Express', tagline: 'Garantias que reduzem objeções', icone: ShieldCheck, cor: 'from-blue-600 to-cyan-700', descricao: 'Incondicional, resultado, estendida, tripla.', ilimitado: true, href: '/agentes/garantia', cta: 'Gerar garantia', emBreve: false },
  { id: 'checkoutmax', nome: 'CheckoutMax', tagline: 'Checkout com gatilhos psicológicos', icone: MousePointerClick, cor: 'from-blue-500 to-blue-700', descricao: 'Pop-ups, selos, contadores, prova social.', ilimitado: false, href: '/agentes/checkoutmax', cta: 'Otimizar checkout', emBreve: false },
  { id: 'scarcitypro', nome: 'ScarcityPro', tagline: 'Urgência ÉTICA (sem fake)', icone: Timer, cor: 'from-red-500 to-red-700', descricao: 'Escassez baseada em capacidade real.', ilimitado: false, href: '/agentes/scarcitypro', cta: 'Criar urgência', emBreve: false },
  { id: 'provaosocialpro', nome: 'Prova Social Pro', tagline: 'Depoimentos que convencem', icone: Users, cor: 'from-pink-500 to-pink-700', descricao: 'Templates de depoimentos reais.', ilimitado: false, href: '/agentes/provaosocialpro', cta: 'Gerar modelos', emBreve: false },
  { id: 'emailboasvindas', nome: 'Boas-Vindas Email', tagline: 'Onboarding que reduz refund', icone: Mail, cor: 'from-indigo-500 to-indigo-700', descricao: 'Sequência de 5 emails pós-compra.', ilimitado: false, href: '/agentes/emailboasvindas', cta: 'Criar sequência', emBreve: false },
  { id: 'leadmagnet', nome: 'Lead Magnet', tagline: 'Iscas digitais éticas', icone: Zap, cor: 'from-cyan-500 to-cyan-700', descricao: 'Checklists, planilhas, quizzes, mini-cursos.', ilimitado: false, href: '/agentes/leadmagnet', cta: 'Gerar isca', emBreve: false },
  { id: 'whatsappvendas', nome: 'WhatsApp Vendas', tagline: 'Scripts de venda por DM', icone: MessageCircle, cor: 'from-green-500 to-green-700', descricao: 'Saudação, objeções, fechamento.', ilimitado: false, href: '/agentes/whatsappvendas', cta: 'Gerar scripts', emBreve: false },
  { id: 'ofertarelampago', nome: 'Oferta Relâmpago', tagline: 'Promoção 24h completa', icone: Zap, cor: 'from-yellow-500 to-yellow-700', descricao: 'Títulos, scripts, checkpoints.', ilimitado: false, href: '/agentes/ofertarelampago', cta: 'Criar oferta', emBreve: false },
  { id: 'bundlecriador', nome: 'Bundle Criador', tagline: 'Combos que aumentam ticket', icone: Layers, cor: 'from-orange-500 to-orange-700', descricao: 'Starter/Pro/VIP com descontos progressivos.', ilimitado: false, href: '/agentes/bundlecriador', cta: 'Criar combo', emBreve: false },
  { id: 'faqobjetor', nome: 'FAQ Objetor', tagline: 'FAQs que matam objeções', icone: HelpCircle, cor: 'from-violet-500 to-violet-700', descricao: 'Perguntas que todo comprador faz.', ilimitado: true, href: '/agentes/faqobjetor', cta: 'Gerar FAQ', emBreve: false },
  { id: 'quizvendas', nome: 'Quiz Vendas', tagline: 'Quiz que converte 3x mais', icone: HelpCircle, cor: 'from-purple-500 to-purple-700', descricao: '4 perguntas que segmentam leads.', ilimitado: false, href: '/agentes/quizvendas', cta: 'Criar quiz', emBreve: false },
  { id: 'captionvendas', nome: 'Caption de Vendas', tagline: 'Legendas de Reels/TikTok', icone: PenTool, cor: 'from-rose-500 to-rose-700', descricao: 'PAS, hooks, CTAs.', ilimitado: false, href: '/agentes/captionvendas', cta: 'Gerar legenda', emBreve: false },
  { id: 'refundminimizer', nome: 'Refund Minimizer', tagline: 'Reduz reembolsos', icone: ShieldOff, cor: 'from-emerald-500 to-emerald-700', descricao: 'Onboarding e mensagens que reduzem devoluções.', ilimitado: false, href: '/agentes/refundminimizer', cta: 'Ver estratégias', emBreve: false },
  { id: 'afiliadorpro', nome: 'Afiliador Pro', tagline: 'Programa de afiliados magnético', icone: Handshake, cor: 'from-amber-500 to-amber-700', descricao: 'Comissão, materiais, regras.', ilimitado: false, href: '/agentes/afiliadorpro', cta: 'Criar programa', emBreve: false },
  { id: 'metodohero', nome: 'Método Hero', tagline: 'Nome e promessa de método', icone: Award, cor: 'from-sky-500 to-sky-700', descricao: 'Sugere 25 nomes para seu método/curso.', ilimitado: false, href: '/agentes/metodohero', cta: 'Nomear método', emBreve: false },
  { id: 'nomesdominio', nome: 'Nomes Domínio', tagline: 'Nomes de marca memoráveis', icone: Type, cor: 'from-teal-500 to-teal-700', descricao: '18 sugestões + regras de ouro.', ilimitado: true, href: '/agentes/nomesdominio', cta: 'Sugerir nomes', emBreve: false },
  { id: 'checklistvp', nome: 'Checklist VP', tagline: 'Checklist de página de vendas', icone: ListChecks, cor: 'from-lime-500 to-lime-700', descricao: '15 pontos obrigatórios.', ilimitado: true, href: '/agentes/checklistvp', cta: 'Ver checklist', emBreve: false },
  { id: 'clientepravida', nome: 'Cliente Pra Vida', tagline: 'Retenção e LTV', icone: Heart, cor: 'from-fuchsia-500 to-fuchsia-700', descricao: '5 estratégias de fidelização.', ilimitado: true, href: '/agentes/clientepravida', cta: 'Ver estratégias', emBreve: false },
  { id: 'scriptbotresposta', nome: 'Script Bot Resposta', tagline: 'Fluxos de bot WhatsApp', icone: Bot, cor: 'from-slate-500 to-slate-700', descricao: 'Mensagens automáticas com opção humano.', ilimitado: false, href: '/agentes/scriptbotresposta', cta: 'Gerar fluxos', emBreve: false },
  { id: 'viralloop', nome: 'Viral Loop', tagline: 'Indicação premiada', icone: Repeat, cor: 'from-pink-500 to-purple-700', descricao: 'Mecânica de indicação.', ilimitado: true, href: '/agentes/viralloop', cta: 'Criar loop', emBreve: false },
  { id: 'kdcalculator', nome: 'KD Calculator', tagline: 'Calcula cashback KD Points', icone: Coins, cor: 'from-yellow-400 to-yellow-600', descricao: '100 KD = R$1, máx 50% desconto.', ilimitado: true, href: '/agentes/kdcalculator', cta: 'Calcular KD', emBreve: false },
  { id: 'abtestideas', nome: 'AB Test Ideas', tagline: 'Testes A/B com maior impacto', icone: GitCompare, cor: 'from-blue-400 to-cyan-600', descricao: 'Testes em checkout/landing/anúncio.', ilimitado: true, href: '/agentes/abtestideas', cta: 'Ver ideias', emBreve: false },
  { id: 'socialcopy', nome: 'Social Copy', tagline: 'Posts X/IG/LinkedIn', icone: Instagram, cor: 'from-red-400 to-pink-600', descricao: 'Posts prontos para 3 redes.', ilimitado: false, href: '/agentes/socialcopy', cta: 'Gerar posts', emBreve: false },
  { id: 'cancelasaver', nome: 'Cancela Saver', tagline: 'Salva cancelamento de assinatura', icone: Shield, cor: 'from-emerald-600 to-green-800', descricao: 'Fluxo de retenção por motivo.', ilimitado: false, href: '/agentes/cancelasaver', cta: 'Ver fluxo', emBreve: false },
  { id: 'seotags', nome: 'SEO Tags', tagline: 'Title + description otimizados', icone: Search, cor: 'from-blue-600 to-indigo-800', descricao: 'Tags para Google e buscadores.', ilimitado: true, href: '/agentes/seotags', cta: 'Gerar tags', emBreve: false },
  { id: 'precoguerra', nome: 'Preço de Guerra', tagline: 'Black Friday sem prejuízo', icone: ShieldAlert, cor: 'from-red-600 to-black', descricao: 'Faixas de desconto seguras.', ilimitado: false, href: '/agentes/precoguerra', cta: 'Calcular BF', emBreve: false },
  // v9.1
  { id: 'saquesimulator', nome: 'Simulador de Saque', tagline: 'Quanto chega PIX', icone: ArrowDownToLine, cor: 'from-green-500 to-emerald-700', descricao: 'Taxa fixa R$0,99, saque mínimo R$30.', ilimitado: true, href: '/agentes/saquesimulator', cta: 'Simular saque', emBreve: false },
  { id: 'precoassinatura', nome: 'Preço Assinatura', tagline: 'Mensal/trimestral/anual', icone: Repeat, cor: 'from-blue-500 to-indigo-700', descricao: 'Preço de assinatura ideal.', ilimitado: false, href: '/agentes/precoassinatura', cta: 'Precificar', emBreve: false },
  { id: 'upsellcarrinho', nome: 'Upsell Carrinho', tagline: 'Bump + upsell no carrinho', icone: ShoppingCart, cor: 'from-purple-500 to-pink-600', descricao: 'Sugestão automática.', ilimitado: false, href: '/agentes/upsellcarrinho', cta: 'Gerar', emBreve: false },
  { id: 'cupomrelampago', nome: 'Cupom Relâmpago', tagline: 'Cupom de 2h para KD', icone: Zap, cor: 'from-yellow-500 to-orange-600', descricao: 'Gera código automático.', ilimitado: false, href: '/agentes/cupomrelampago', cta: 'Gerar cupom', emBreve: false },
  { id: 'upgradeplano', nome: 'Oferta Upgrade', tagline: 'Convence a subir de plano', icone: BadgeCheck, cor: 'from-emerald-500 to-teal-700', descricao: 'Cálculo de economia de taxa.', ilimitado: false, href: '/agentes/upgradeplano', cta: 'Gerar oferta', emBreve: false },
  { id: 'vendacruzada', nome: 'Venda Cruzada', tagline: 'Produtos que combinam', icone: GitBranch, cor: 'from-rose-500 to-pink-700', descricao: 'Recomendações inteligentes.', ilimitado: false, href: '/agentes/vendacruzada', cta: 'Sugerir', emBreve: false },
  { id: 'boasvindas', nome: 'Boas-Vindas Compra', tagline: 'Mensagem pós-compra', icone: Gift, cor: 'from-pink-500 to-fuchsia-700', descricao: 'Mensagem + bônus KD.', ilimitado: false, href: '/agentes/boasvindas', cta: 'Gerar mensagem', emBreve: false },
  { id: 'roiads', nome: 'ROI de Anúncios', tagline: 'Calcula se tráfego pago dá lucro', icone: BarChart3, cor: 'from-orange-500 to-red-700', descricao: 'CAC, ROI, decisão.', ilimitado: true, href: '/agentes/roiads', cta: 'Calcular ROI', emBreve: false },
  { id: 'bfstrategy', nome: 'Black Friday Playbook', tagline: 'Estratégia BF completa', icone: Flame, cor: 'from-slate-800 to-black', descricao: 'Pré-BF, sexta, sábado, Cyber Monday.', ilimitado: false, href: '/agentes/bfstrategy', cta: 'Ver playbook', emBreve: false },
  { id: 'mrrcalc', nome: 'MRR Calculator', tagline: 'Receita recorrente e LTV', icone: TrendingUp, cor: 'from-cyan-500 to-blue-700', descricao: 'MRR, ARR, LTV, churn.', ilimitado: true, href: '/agentes/mrrcalc', cta: 'Calcular MRR', emBreve: false },
  { id: 'sniperlancamento', nome: 'Script Lançamento 7d', tagline: 'Cronograma de lançamento', icone: Target, cor: 'from-violet-500 to-purple-700', descricao: '7 dias de pré + abertura + fechamento.', ilimitado: false, href: '/agentes/sniperlancamento', cta: 'Gerar cronograma', emBreve: false },
  { id: 'copysniper', nome: 'Copy Lançamento', tagline: 'Emails que convertem', icone: PenTool, cor: 'from-red-500 to-rose-700', descricao: 'Sequência de emails de lançamento.', ilimitado: false, href: '/agentes/copysniper', cta: 'Gerar emails', emBreve: false },
  { id: 'pitchvenda', nome: "Pitch de Vendas", tagline: "30s/1min/DM/Reels", icone: Sparkles, cor: 'orange-500 red-600', descricao: "30s/1min/DM/Reels", ilimitado: false, href: '/agentes/pitchvenda', cta: 'Usar', emBreve: false },
  { id: 'chargedefense', nome: "Defesa Chargeback", tagline: "Recupera disputa e evita multas", icone: Sparkles, cor: 'red-700 black', descricao: "Recupera disputa e evita multas", ilimitado: false, href: '/agentes/chargedefense', cta: 'Usar', emBreve: false },
  { id: 'reviewreply', nome: "Respondedor de Reviews", tagline: "Responde 1-5 estrelas com tom certo", icone: Sparkles, cor: 'amber-500 yellow-600', descricao: "Responde 1-5 estrelas com tom certo", ilimitado: false, href: '/agentes/reviewreply', cta: 'Usar', emBreve: false },
  { id: 'precodinamico', nome: "Precificação Dinâmica", tagline: "Preço em 7 cenários diferentes", icone: Sparkles, cor: 'teal-500 cyan-700', descricao: "Preço em 7 cenários diferentes", ilimitado: false, href: '/agentes/precodinamico', cta: 'Usar', emBreve: false },
  { id: 'hookcriador', nome: "Hook de Anúncio", tagline: "10 hooks que param o scroll", icone: Sparkles, cor: 'pink-500 red-600', descricao: "10 hooks que param o scroll", ilimitado: false, href: '/agentes/hookcriador', cta: 'Usar', emBreve: false },
  { id: 'criativoads', nome: "Criativo de Anúncio", tagline: "Roteiro 35seg + thumbs + legenda", icone: Sparkles, cor: 'purple-500 fuchsia-700', descricao: "Roteiro 35seg + thumbs + legenda", ilimitado: false, href: '/agentes/criativoads', cta: 'Usar', emBreve: false },
  { id: 'pitchdeck', nome: "Pitch Deck", tagline: "10 slides pra parceria/investidor", icone: Sparkles, cor: 'indigo-500 blue-700', descricao: "10 slides pra parceria/investidor", ilimitado: false, href: '/agentes/pitchdeck', cta: 'Usar', emBreve: false },
  { id: 'contratoafiliado', nome: "Minuta Afiliado", tagline: "10 cláusulas essenciais", icone: Sparkles, cor: 'slate-600 slate-900', descricao: "10 cláusulas essenciais", ilimitado: false, href: '/agentes/contratoafiliado', cta: 'Usar', emBreve: false },
  { id: 'npsfollow', nome: "NPS Follow-Up", tagline: "Pesquisa e ação por nota", icone: Sparkles, cor: 'cyan-500 teal-600', descricao: "Pesquisa e ação por nota", ilimitado: false, href: '/agentes/npsfollow', cta: 'Usar', emBreve: false },
  { id: 'posvenda', nome: "Sequência Pós-Venda", tagline: "8 contatos que reduzem refund 40%", icone: Sparkles, cor: 'blue-500 indigo-700', descricao: "8 contatos que reduzem refund 40%", ilimitado: false, href: '/agentes/posvenda', cta: 'Usar', emBreve: false },
  { id: 'bonusmaker', nome: "Gerador de Bônus", tagline: "Bônus de alto valor sem custo", icone: Sparkles, cor: 'rose-500 pink-700', descricao: "Bônus de alto valor sem custo", ilimitado: false, href: '/agentes/bonusmaker', cta: 'Usar', emBreve: false },
  { id: 'valorpercebido', nome: "Valor Percebido", tagline: "Calcula valor x preço da oferta", icone: Sparkles, cor: 'violet-500 purple-700', descricao: "Calcula valor x preço da oferta", ilimitado: false, href: '/agentes/valorpercebido', cta: 'Usar', emBreve: false },
  // v10 MONSTER — 22 novos agentes (Black Friday, TikTok, ROI, etc)
  { id: 'blackfridayplaybook', nome: 'Black Friday Playbook', tagline: 'Estratégia BF 30 dias completa', icone: Flame, cor: 'from-red-600 to-orange-600', descricao: 'Calendário, preços, emails e copy para vender muito na Black Friday sem erro.', ilimitado: false, href: '/agentes/blackfridayplaybook', cta: 'Gerar estratégia', emBreve: false },
  { id: 'leadmagnetpro', nome: 'Lead Magnet Pro', tagline: 'Isca digital que converte 20-40%', icone: Magnet, cor: 'from-blue-500 to-cyan-600', descricao: 'Cria checklists, ebooks e templates irresistíveis com página de captura pronta.', ilimitado: true, href: '/agentes/leadmagnetpro', cta: 'Criar isca', emBreve: false },
  { id: 'tiktokscripts', nome: 'TikTok & Reels Scripts', tagline: 'Roteiros virais 15s/30s/60s', icone: Clapperboard, cor: 'from-pink-500 to-rose-600', descricao: '6 ângulos de roteiro com hook em 3s, cenas, CTA e hashtags estimadas.', ilimitado: true, href: '/agentes/tiktokscripts', cta: 'Gerar roteiros', emBreve: false },
  { id: 'seolocalpages', nome: 'SEO Local (cidades)', tagline: 'Páginas SEO por cidade', icone: MapPin, cor: 'from-emerald-500 to-green-600', descricao: 'Gera páginas otimizadas para cidade+nicho (rankeamento local).', ilimitado: false, href: '/agentes/seolocalpages', cta: 'Gerar páginas', emBreve: false },
  { id: 'roiads', nome: 'Calculadora ROI Ads', tagline: 'ROI/ROAS real em 3 cenários', icone: BarChart3, cor: 'from-indigo-500 to-purple-600', descricao: 'Calcule lucro líquido de anúncios Meta/Google/TikTok com pessimista/realista/otimista.', ilimitado: true, href: '/agentes/roiads', cta: 'Calcular', emBreve: false },
  { id: 'upsellquiz', nome: 'Quiz de Upsell', tagline: '+40% no ticket médio', icone: Target, cor: 'from-violet-500 to-purple-700', descricao: 'Quiz inteligente que recomenda o pacote ideal (starter/pro/vip) para cada cliente.', ilimitado: false, href: '/agentes/upsellquiz', cta: 'Criar quiz', emBreve: false },
  { id: 'canvaprompts', nome: 'Prompts Canva/Midjourney', tagline: 'Criativos profissionais em 1 clique', icone: Palette, cor: 'from-fuchsia-500 to-pink-600', descricao: '5 prompts por tipo de arte (story, feed, banner, thumbnail, logo) com aspect ratio.', ilimitado: true, href: '/agentes/canvaprompts', cta: 'Gerar prompts', emBreve: false },
  { id: 'hotjarheatmap', nome: 'Auditoria Heatmap', tagline: 'CRO heurístico em segundos', icone: Flame, cor: 'from-orange-500 to-red-600', descricao: 'Detecta os problemas de conversão na sua página com score e correções.', ilimitado: false, href: '/agentes/hotjarheatmap', cta: 'Auditar', emBreve: false },
  { id: 'emailswipefile', nome: 'Email Swipe File', tagline: '100+ assuntos que abrem', icone: Mail, cor: 'from-sky-500 to-blue-700', descricao: 'Assuntos e templates de email para boas-vindas, carrinho, lançamento e BF.', ilimitado: true, href: '/agentes/emailswipefile', cta: 'Ver swipe file', emBreve: false },
  { id: 'whatsappfunnel', nome: 'Funil de WhatsApp', tagline: 'Sequência WPP que converte', icone: MessageCircle, cor: 'from-green-500 to-emerald-600', descricao: 'Boas-vindas, aquecimento, oferta, resposta a objeções e fechamento.', ilimitado: false, href: '/agentes/whatsappfunnel', cta: 'Criar funil', emBreve: false },
  { id: 'instagramgrid', nome: 'Instagram Grid Planner', tagline: 'Bio, posts e calendário 30d', icone: Camera, cor: 'from-pink-500 to-fuchsia-600', descricao: '9/18 posts, biografia, destaques e calendário completo de 30 dias.', ilimitado: true, href: '/agentes/instagramgrid', cta: 'Planejar grid', emBreve: false },
  { id: 'reviewrequest', nome: 'Pedido de Review', tagline: '+40% avaliações', icone: Star, cor: 'from-yellow-400 to-orange-500', descricao: 'Emails e WhatsApp que fazem clientes deixarem reviews honestas.', ilimitado: true, href: '/agentes/reviewrequest', cta: 'Criar pedido', emBreve: false },
  { id: 'salespageminimalista', nome: 'Página de Vendas', tagline: 'Estrutura 3-8% conversão', icone: Banknote, cor: 'from-slate-800 to-black', descricao: 'Estrutura completa de sales page com copy pronta e ordem das seções.', ilimitado: false, href: '/agentes/salespageminimalista', cta: 'Criar estrutura', emBreve: false },
  { id: 'podcastguestpitch', nome: 'Pitch Podcast/YouTube', tagline: 'Seja convidado e ganhe autoridade', icone: Mic, cor: 'from-red-500 to-rose-700', descricao: 'Templates de email para ser convidado em podcasts e canais.', ilimitado: false, href: '/agentes/podcastguestpitch', cta: 'Gerar pitch', emBreve: false },
  { id: 'croaudit', nome: 'Auditoria CRO', tagline: 'Score de conversão + checklist', icone: TrendingUp, cor: 'from-teal-500 to-cyan-700', descricao: 'Auditoria com score de 0-100, falhas e checklist de correção.', ilimitado: true, href: '/agentes/croaudit', cta: 'Auditar página', emBreve: false },
  { id: 'kdpointscampaign', nome: 'Campanha KD Points', tagline: 'Fidelidade que gera recompra', icone: Gem, cor: 'from-amber-400 to-yellow-500', descricao: 'Crie campanhas de KD Points para cadastro, compra, review e indicação.', ilimitado: true, href: '/agentes/kdpointscampaign', cta: 'Criar campanha', emBreve: false },
  { id: 'plrspinner', nome: 'Reescrever PLR', tagline: 'Conteúdo original sem penalidade', icone: RefreshCw, cor: 'from-cyan-500 to-blue-600', descricao: 'Reescreve PLR para ficar 100% original e rankear no Google.', ilimitado: false, href: '/agentes/plrspinner', cta: 'Reescrever', emBreve: false },
  { id: 'launchecklist30d', nome: 'Checklist Lançamento 30d', tagline: 'Do zero ao carrinho aberto', icone: Rocket, cor: 'from-indigo-600 to-violet-700', descricao: 'Tarefas diárias por 30 dias para lançar produto com faturamento previsto.', ilimitado: true, href: '/agentes/launchecklist30d', cta: 'Gerar checklist', emBreve: false },
  { id: 'vslgenerator', nome: 'Gerador de VSL', tagline: 'Script VSL 10 min', icone: Video, cor: 'from-red-600 to-rose-800', descricao: 'VSL completa com 10 slides, tempo, narração e dicas de performance.', ilimitado: false, href: '/agentes/vslgenerator', cta: 'Gerar VSL', emBreve: false },
  { id: 'churnreduce', nome: 'Reduzir Churn', tagline: '-15-30% cancelamentos', icone: Shield, cor: 'from-emerald-600 to-teal-700', descricao: 'Emails preventivos, fluxo de cancelamento e campanhas winback.', ilimitado: false, href: '/agentes/churnreduce', cta: 'Gerar fluxos', emBreve: false },
  { id: 'webhooktest', nome: 'Teste de Webhook', tagline: 'Payloads Stripe prontos', icone: Plug, cor: 'from-slate-600 to-slate-800', descricao: 'Gera payloads de teste para todos os eventos Stripe (checkout, assinatura, saque).', ilimitado: false, href: '/agentes/webhooktest', cta: 'Gerar payload', emBreve: false },
  { id: 'bolsadeapostas', nome: 'Dutching/Apostas', tagline: 'Calculadora arbitragem', icone: Dices, cor: 'from-green-600 to-emerald-800', descricao: 'Calcule valores para apostar em múltiplas odds e lucrar independente do resultado.', ilimitado: true, href: '/agentes/bolsadeapostas', cta: 'Calcular', emBreve: false },
]

export default function AgentsPage() {
  return (
    <div className="min-h-screen bg-[#FAFAFA] dark:bg-[#0B0F1A] pt-24 pb-20">
      <div className="max-w-7xl mx-auto px-5 md:px-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-14">
          <div className="inline-flex items-center gap-2 rounded-full bg-[#2563EB]/10 px-4 py-1.5 mb-5">
            <Sparkles size={14} className="text-[#2563EB]" />
            <span className="text-[11px] font-black uppercase tracking-widest text-[#2563EB]">
              KIYVO Agents • Powered by Kiya
            </span>
          </div>
          <h1 className="text-4xl md:text-6xl font-black tracking-tight text-[#0F172A] dark:text-white leading-[0.95] mb-5">
            {AGENTS.length} agentes IA <br className="hidden md:block" />
            <span className="bg-gradient-to-r from-[#2563EB] via-[#7C3AED] to-[#EC4899] bg-clip-text text-transparent">
              trabalhando pra você vender mais.
            </span>
          </h1>
          <p className="text-lg md:text-xl text-[#64748B] dark:text-slate-400 max-w-2xl">
            Banners, copy, preços, SEO, traduções, anúncios, atendimento, promoções — tudo em um só lugar.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {AGENTS.map((agent, i) => {
            const Icon = agent.icone
            return (
              <motion.div key={agent.id} initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: (i % 9) * 0.06 }}>
                <Link href={agent.href}
                  className={`group block h-full rounded-[2rem] bg-white dark:bg-[#0F172A] border border-black/5 dark:border-white/5 p-7 shadow-sm hover:shadow-xl transition-all hover:-translate-y-1 ${agent.emBreve ? 'opacity-60 pointer-events-none' : ''}`}>
                  <div className={`w-14 h-14 rounded-2xl bg-gradient-to-br ${agent.cor} flex items-center justify-center mb-5 shadow-lg`}>
                    <Icon size={28} className="text-white" />
                  </div>
                  <div className="flex items-center gap-2 mb-2 flex-wrap">
                    <h3 className="text-xl font-black text-[#0F172A] dark:text-white">{agent.nome}</h3>
                    {agent.ilimitado && (
                      <span className="text-[10px] font-black uppercase tracking-wider bg-emerald-500/15 text-emerald-600 px-2 py-0.5 rounded-full">Grátis • Ilimitado</span>
                    )}
                  </div>
                  <p className="text-sm font-semibold text-[#2563EB] dark:text-[#60A5FA] mb-3">{agent.tagline}</p>
                  <p className="text-sm text-[#64748B] dark:text-slate-400 leading-relaxed mb-5">{agent.descricao}</p>
                  <div className="inline-flex items-center gap-1.5 text-sm font-black text-[#0F172A] dark:text-white group-hover:text-[#2563EB]">
                    {agent.cta} <ChevronRight size={16} className="transition-transform group-hover:translate-x-1" />
                  </div>
                </Link>
              </motion.div>
            )
          })}
        </div>

        <div className="mt-16 rounded-[2rem] bg-gradient-to-br from-[#0F172A] to-[#1E293B] p-10 md:p-14 text-white">
          <div className="flex items-start gap-4 mb-4">
            <div className="w-12 h-12 rounded-2xl bg-white/10 flex items-center justify-center flex-shrink-0">
              <Heart size={22} className="text-rose-400" />
            </div>
            <div>
              <h2 className="text-2xl md:text-3xl font-black mb-2">Kiya Widget em todas as páginas</h2>
              <p className="text-slate-300 max-w-2xl">
                O botão flutuante verde no canto inferior direito abre o chat da Kiya a qualquer momento —
                suporte 24h sem sair do site.
              </p>
            </div>
          </div>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link href="/suporte" className="inline-flex items-center gap-2 rounded-full bg-white text-[#0F172A] font-black px-6 py-3 text-sm hover:scale-105 transition-transform">
              Abrir Kiya <ChevronRight size={16} />
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}
