'use client'; import { useState } from 'react'; import { LayoutTemplate } from 'lucide-react'; import { AgentShell, Field, inputClass } from '@/components/agents/AgentShell';
export default function Page(){const[produto,setProduto]=useState('');const[nicho,setNicho]=useState('');const[preco,setPreco]=useState('97');const[beneficios,setBeneficios]=useState('');const[formato,setFormato]=useState('hybrid');const[loading,setLoading]=useState(false);const[out,setOut]=useState<any>(null);
const gerar=async()=>{setLoading(true);try{const r=await fetch('/api/agents/landingforge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({produto,preco:Number(preco),nicho,beneficios:beneficios.split('\n').filter(Boolean),formato})});const d=await r.json();if(d.error)return alert(d.error);setOut(d)}catch{alert('Erro')}finally{setLoading(false)}}
return(<AgentShell titulo="LandingForge" tagline="Estrutura completa de landing page de alta conversão (seção por seção)" icone={<LayoutTemplate className="w-7 h-7"/>} cor="bg-gradient-to-br from-indigo-500 to-blue-700" labelBotao="Gerar estrutura" onGerar={gerar} loading={loading} output={out && (
<div className="space-y-3">
<div className="bg-gradient-to-br from-indigo-500 to-blue-700 text-white rounded-2xl p-5"><p className="text-[10px] font-black uppercase opacity-80">Headline</p><p className="text-xl font-black mt-1">{out.headline}</p><p className="text-sm opacity-90 mt-1">{out.subheadline}</p><div className="mt-3 bg-white text-[#0F172A] rounded-full py-2 px-4 text-center text-sm font-black">{out.ctaPrincipal}</div></div>
<p className="text-[11px] font-black uppercase tracking-widest text-slate-500">Seções na ordem:</p>
<div className="space-y-2">{out.estrutura.map((s:any,i:number)=>(<details key={i} className="bg-white dark:bg-[#111827] border border-slate-200 dark:border-slate-800 rounded-xl p-3"><summary className="font-bold cursor-pointer text-sm"><span className="text-brand-600 font-black mr-2">{i+1}.</span>{s.titulo} <span className="text-[10px] text-slate-400 ml-1">({s.tipo})</span></summary><pre className="text-xs whitespace-pre-wrap mt-2 text-slate-600 dark:text-slate-300 font-sans bg-slate-50 dark:bg-[#0B0F1A] p-2 rounded-lg">{s.conteudo}</pre>{s.dicaDesign && <p className="text-[10px] text-amber-700 mt-1">💡 {s.dicaDesign}</p>}</details>))}</div>
<details className="bg-slate-50 dark:bg-[#0B0F1A] rounded-xl p-3 text-xs"><summary className="font-bold">❓ FAQ sugerido</summary><ul className="mt-2 space-y-1">{out.faqPerguntas.map((f:any,i:number)=><li key={i}><strong>{f.pergunta}</strong><br/>{f.resposta}</li>)}</ul></details>
<div className="bg-emerald-50 dark:bg-emerald-900/20 rounded-xl p-3 text-xs"><p className="font-black text-emerald-700">Dicas de conversão (conversão estimada {out.scoreConversaoEstimado.toFixed(1)}%):</p><ul className="mt-1 space-y-1 text-slate-700 dark:text-slate-300">{out.dicas.map((d:string,i:number)=><li key={i}>{d}</li>)}</ul></div>
<p className="text-[10px]"><strong>Meta Title:</strong> {out.metaTitle}<br/><strong>Meta Description:</strong> {out.metaDescription}</p>
</div>)}>
<Field label="Produto"><input className={inputClass} value={produto} onChange={e=>setProduto(e.target.value)} placeholder="Ex: Método ReelsPro"/></Field>
<Field label="Nicho"><input className={inputClass} value={nicho} onChange={e=>setNicho(e.target.value)} placeholder="Ex: marketing digital"/></Field>
<Field label="Preço R$"><input className={inputClass} type="number" value={preco} onChange={e=>setPreco(e.target.value)}/></Field>
<Field label="Benefícios (um por linha)"><textarea className={inputClass+' min-h-[100px]'} value={beneficios} onChange={e=>setBeneficios(e.target.value)} placeholder={"Resultado em 7 dias\nGarantia incondicional\nPasso a passo simples"}/></Field>
</AgentShell>)}
