// Produtos demo reais da KIYVO — gerados para parecerem vendedores reais.
// Quando o Supabase não estiver conectado (ou a tabela estiver vazia), estes produtos aparecem.
// Para adicionar mais produtos cadastre-os no painel vendedor ou via SQL no Supabase.

export interface DemoProduct {
  id: string
  slug: string
  titulo: string
  descricao_curta: string
  descricao: string
  preco: number
  preco_de: number
  categoria: string
  tipo: string
  vendedor_nome: string
  vendor_id: string
  gradient: string
  emoji: string
  imagem_capa: string | null
  rating: number
  total_reviews: number
  total_vendas: number
  boost: boolean
  created_at: string
}

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    "id": "d-001",
    "slug": "metodo-trafego-zero-venda-sem-anunciar",
    "titulo": "Método Tráfego Zero — Venda Sem Anunciar",
    "descricao_curta": "Estratégia orgânica de vendas no Instagram e TikTok usando conteúdo gratuito que viraliza.",
    "descricao": "Estratégia orgânica de vendas no Instagram e TikTok usando conteúdo gratuito que viraliza. Construído por Bruno Silva com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 97,
    "preco_de": 297,
    "categoria": "marketing",
    "tipo": "curso",
    "vendedor_nome": "Bruno Silva",
    "vendor_id": "d-001-v",
    "gradient": "from-orange-400 to-red-500",
    "emoji": "📈",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 412,
    "total_vendas": 3890,
    "boost": true,
    "created_at": "2026-06-20T01:49:15.992Z"
  },
  {
    "id": "d-002",
    "slug": "copywriting-pro-escreva-vsl-que-vende",
    "titulo": "Copywriting Pro — Escreva VSL que Vende",
    "descricao_curta": "18 módulos ensinando a escrever copy que converte de 3% a 8% sem precisar aparecer.",
    "descricao": "18 módulos ensinando a escrever copy que converte de 3% a 8% sem precisar aparecer. Construído por Larissa Mendes com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 147,
    "preco_de": 497,
    "categoria": "copywriting",
    "tipo": "curso",
    "vendedor_nome": "Larissa Mendes",
    "vendor_id": "d-002-v",
    "gradient": "from-purple-500 to-pink-600",
    "emoji": "✍️",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 289,
    "total_vendas": 2104,
    "boost": false,
    "created_at": "2026-06-22T01:49:16.000Z"
  },
  {
    "id": "d-003",
    "slug": "planilha-financeira-para-mei-automatizada",
    "titulo": "Planilha Financeira para MEI Automatizada",
    "descricao_curta": "Controle entradas, saídas, DAS, IRRF, pró-labore e emita relatórios em 1 clique.",
    "descricao": "Controle entradas, saídas, DAS, IRRF, pró-labore e emita relatórios em 1 clique. Construído por ContaAqui com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 27,
    "preco_de": 97,
    "categoria": "planilhas",
    "tipo": "planilha",
    "vendedor_nome": "ContaAqui",
    "vendor_id": "d-003-v",
    "gradient": "from-emerald-400 to-teal-600",
    "emoji": "📊",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 1203,
    "total_vendas": 9821,
    "boost": true,
    "created_at": "2026-05-27T01:49:16.000Z"
  },
  {
    "id": "d-004",
    "slug": "pack-1000-prompts-chatgpt-para-negocios",
    "titulo": "Pack 1000 Prompts ChatGPT para Negócios",
    "descricao_curta": "1.000 prompts testados e organizados por categoria: vendas, marketing, atendimento e mais.",
    "descricao": "1.000 prompts testados e organizados por categoria: vendas, marketing, atendimento e mais. Construído por PromptKing BR com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 37,
    "preco_de": 147,
    "categoria": "prompts",
    "tipo": "pack",
    "vendedor_nome": "PromptKing BR",
    "vendor_id": "d-004-v",
    "gradient": "from-cyan-500 to-blue-600",
    "emoji": "🤖",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 542,
    "total_vendas": 4201,
    "boost": true,
    "created_at": "2026-06-11T01:49:16.000Z"
  },
  {
    "id": "d-005",
    "slug": "canva-designer-pro-templates-editaveis",
    "titulo": "Canva Designer Pro — Templates Editáveis",
    "descricao_curta": "300 templates Canva para posts, reels, stories, capas e thumbnails 100% editáveis.",
    "descricao": "300 templates Canva para posts, reels, stories, capas e thumbnails 100% editáveis. Construído por StudioCriativo com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 47,
    "preco_de": 197,
    "categoria": "templates",
    "tipo": "template",
    "vendedor_nome": "StudioCriativo",
    "vendor_id": "d-005-v",
    "gradient": "from-pink-500 to-rose-600",
    "emoji": "🎨",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 678,
    "total_vendas": 5432,
    "boost": true,
    "created_at": "2026-06-10T01:49:16.000Z"
  },
  {
    "id": "d-006",
    "slug": "mentoria-freelancer-mil-saia-do-zero",
    "titulo": "Mentoria Freelancer Mil — Saia do Zero",
    "descricao_curta": "6 semanas de acompanhamento saindo de R$0 para R$5k/mês como freelancer.",
    "descricao": "6 semanas de acompanhamento saindo de R$0 para R$5k/mês como freelancer. Construído por Ana Freitas com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 497,
    "preco_de": 1497,
    "categoria": "mentoria",
    "tipo": "mentoria",
    "vendedor_nome": "Ana Freitas",
    "vendor_id": "d-006-v",
    "gradient": "from-indigo-500 to-violet-700",
    "emoji": "🎯",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 84,
    "total_vendas": 267,
    "boost": false,
    "created_at": "2026-07-13T01:49:16.000Z"
  },
  {
    "id": "d-007",
    "slug": "reels-virais-formula-6-engates",
    "titulo": "Reels Virais — Fórmula 6 Engates",
    "descricao_curta": "Método simples de 6 hooks que geram vídeos com +100k views organicamente.",
    "descricao": "Método simples de 6 hooks que geram vídeos com +100k views organicamente. Construído por Viral BR com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 67,
    "preco_de": 197,
    "categoria": "social",
    "tipo": "curso",
    "vendedor_nome": "Viral BR",
    "vendor_id": "d-007-v",
    "gradient": "from-red-500 to-orange-600",
    "emoji": "🎬",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 342,
    "total_vendas": 2891,
    "boost": false,
    "created_at": "2026-06-14T01:49:16.000Z"
  },
  {
    "id": "d-008",
    "slug": "jornada-afiliado-iniciante-7-dias",
    "titulo": "Jornada Afiliado Iniciante 7 Dias",
    "descricao_curta": "Em 7 dias você faz sua primeira venda como afiliado, sem investir em anúncios.",
    "descricao": "Em 7 dias você faz sua primeira venda como afiliado, sem investir em anúncios. Construído por AfiliadoBR com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "afiliados",
    "tipo": "curso",
    "vendedor_nome": "AfiliadoBR",
    "vendor_id": "d-008-v",
    "gradient": "from-green-500 to-emerald-700",
    "emoji": "🌱",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 891,
    "total_vendas": 12320,
    "boost": true,
    "created_at": "2026-06-13T01:49:16.000Z"
  },
  {
    "id": "d-009",
    "slug": "pack-cnpj-simples-abra-empresa-sozinho",
    "titulo": "Pack CNPJ Simples — Abra Empresa Sozinho",
    "descricao_curta": "Passo a passo completo para abrir MEI/ME e economizar R$2k com contador no primeiro ano.",
    "descricao": "Passo a passo completo para abrir MEI/ME e economizar R$2k com contador no primeiro ano. Construído por Legalize Fácil com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 57,
    "preco_de": 197,
    "categoria": "juridico",
    "tipo": "pack",
    "vendedor_nome": "Legalize Fácil",
    "vendor_id": "d-009-v",
    "gradient": "from-slate-600 to-slate-900",
    "emoji": "📋",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 234,
    "total_vendas": 1421,
    "boost": false,
    "created_at": "2026-06-21T01:49:16.000Z"
  },
  {
    "id": "d-010",
    "slug": "receitas-fit-de-15-minutos-200-receitas",
    "titulo": "Receitas Fit de 15 Minutos — 200+ Receitas",
    "descricao_curta": "Ebook com 212 receitas fit rápidas, baixas em calorias e com lista de compras semanal.",
    "descricao": "Ebook com 212 receitas fit rápidas, baixas em calorias e com lista de compras semanal. Construído por Nutri Carol com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 29.9,
    "preco_de": 97,
    "categoria": "saude",
    "tipo": "ebook",
    "vendedor_nome": "Nutri Carol",
    "vendor_id": "d-010-v",
    "gradient": "from-lime-400 to-green-600",
    "emoji": "🥗",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 1567,
    "total_vendas": 8920,
    "boost": true,
    "created_at": "2026-05-31T01:49:16.000Z"
  },
  {
    "id": "d-011",
    "slug": "mindset-milionario-30-dias-de-transformacao",
    "titulo": "Mindset Milionário — 30 Dias de Transformação",
    "descricao_curta": "Áudios diários de 5 minutos, exercícios e meditações guiadas por 30 dias.",
    "descricao": "Áudios diários de 5 minutos, exercícios e meditações guiadas por 30 dias. Construído por Código Mental com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 37,
    "preco_de": 147,
    "categoria": "desenvolvimento",
    "tipo": "curso",
    "vendedor_nome": "Código Mental",
    "vendor_id": "d-011-v",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "🧠",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 423,
    "total_vendas": 3012,
    "boost": true,
    "created_at": "2026-06-28T01:49:16.000Z"
  },
  {
    "id": "d-012",
    "slug": "vsl-killer-template-powerpoint-editavel",
    "titulo": "VSL Killer — Template Powerpoint Editável",
    "descricao_curta": "Template VSL pronto com slides de hook, problema, solução, prova, oferta e fechamento.",
    "descricao": "Template VSL pronto com slides de hook, problema, solução, prova, oferta e fechamento. Construído por VideoScripts com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 47,
    "preco_de": 197,
    "categoria": "templates",
    "tipo": "template",
    "vendedor_nome": "VideoScripts",
    "vendor_id": "d-012-v",
    "gradient": "from-yellow-400 to-orange-500",
    "emoji": "🎞️",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 178,
    "total_vendas": 1098,
    "boost": false,
    "created_at": "2026-07-06T01:49:16.000Z"
  },
  {
    "id": "d-013",
    "slug": "whatsapp-vendas-pro-scripts-e-fluxos",
    "titulo": "WhatsApp Vendas Pro — Scripts e Fluxos",
    "descricao_curta": "Pacote com 87 scripts prontos de WhatsApp para atendimento, objeções e fechamento.",
    "descricao": "Pacote com 87 scripts prontos de WhatsApp para atendimento, objeções e fechamento. Construído por CloseZap com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 67,
    "preco_de": 247,
    "categoria": "vendas",
    "tipo": "pack",
    "vendedor_nome": "CloseZap",
    "vendor_id": "d-013-v",
    "gradient": "from-green-400 to-teal-600",
    "emoji": "💬",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 312,
    "total_vendas": 2671,
    "boost": false,
    "created_at": "2026-06-30T01:49:16.000Z"
  },
  {
    "id": "d-014",
    "slug": "curso-excel-avancado-para-o-trabalho",
    "titulo": "Curso Excel Avançado para o Trabalho",
    "descricao_curta": "Deixe o básico para trás: PROCV, tabela dinâmica, macros, Power Query e dashboards.",
    "descricao": "Deixe o básico para trás: PROCV, tabela dinâmica, macros, Power Query e dashboards. Construído por PlanilhasBR com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 77,
    "preco_de": 297,
    "categoria": "tecnologia",
    "tipo": "curso",
    "vendedor_nome": "PlanilhasBR",
    "vendor_id": "d-014-v",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "📑",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 1023,
    "total_vendas": 7231,
    "boost": true,
    "created_at": "2026-07-07T01:49:16.000Z"
  },
  {
    "id": "d-015",
    "slug": "criacao-de-marca-logo-identidade-visual",
    "titulo": "Criação de Marca — Logo + Identidade Visual",
    "descricao_curta": "Pacote completo: logotipo, paleta, tipografia, cartão de visitas e manual de marca.",
    "descricao": "Pacote completo: logotipo, paleta, tipografia, cartão de visitas e manual de marca. Construído por Marca Criativa Studio com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 297,
    "preco_de": 897,
    "categoria": "design",
    "tipo": "servico",
    "vendedor_nome": "Marca Criativa Studio",
    "vendor_id": "d-015-v",
    "gradient": "from-pink-400 to-fuchsia-600",
    "emoji": "🎯",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 67,
    "total_vendas": 142,
    "boost": false,
    "created_at": "2026-07-17T01:49:16.000Z"
  },
  {
    "id": "d-016",
    "slug": "investidor-iniciante-primeiros-r-100k",
    "titulo": "Investidor Iniciante — Primeiros R$100k",
    "descricao_curta": "Aprenda a investir do zero: CDB, LCI, LCA, Tesouro, ações, FIIs e ETFs sem erro.",
    "descricao": "Aprenda a investir do zero: CDB, LCI, LCA, Tesouro, ações, FIIs e ETFs sem erro. Construído por InvesteJovem com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 197,
    "preco_de": 597,
    "categoria": "financas",
    "tipo": "curso",
    "vendedor_nome": "InvesteJovem",
    "vendor_id": "d-016-v",
    "gradient": "from-teal-500 to-cyan-700",
    "emoji": "💹",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 278,
    "total_vendas": 1823,
    "boost": false,
    "created_at": "2026-06-14T01:49:16.000Z"
  },
  {
    "id": "d-017",
    "slug": "pack-social-media-legendas-hashtags",
    "titulo": "Pack Social Media — Legendas + Hashtags",
    "descricao_curta": "500 legendas prontas + pacote de hashtags segmentadas por nicho para Instagram.",
    "descricao": "500 legendas prontas + pacote de hashtags segmentadas por nicho para Instagram. Construído por Social Prontos com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 39.9,
    "preco_de": 147,
    "categoria": "social",
    "tipo": "pack",
    "vendedor_nome": "Social Prontos",
    "vendor_id": "d-017-v",
    "gradient": "from-fuchsia-500 to-pink-700",
    "emoji": "#️⃣",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 892,
    "total_vendas": 6543,
    "boost": true,
    "created_at": "2026-07-13T01:49:16.000Z"
  },
  {
    "id": "d-018",
    "slug": "ingles-em-6-meses-metodo-autodidata",
    "titulo": "Inglês em 6 Meses — Método Autodidata",
    "descricao_curta": "Método de inglês autodidata baseado em input massivo e repetição espaçada.",
    "descricao": "Método de inglês autodidata baseado em input massivo e repetição espaçada. Construído por Fluente BR com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 127,
    "preco_de": 397,
    "categoria": "idiomas",
    "tipo": "curso",
    "vendedor_nome": "Fluente BR",
    "vendor_id": "d-018-v",
    "gradient": "from-blue-400 to-blue-700",
    "emoji": "🇺🇸",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 567,
    "total_vendas": 3421,
    "boost": true,
    "created_at": "2026-06-25T01:49:16.000Z"
  },
  {
    "id": "d-019",
    "slug": "ebook-receitas-airfryer-300-receitas",
    "titulo": "Ebook Receitas Airfryer 300+ Receitas",
    "descricao_curta": "312 receitas de airfryer: carnes, peixes, legumes, pães, doces e até petiscos.",
    "descricao": "312 receitas de airfryer: carnes, peixes, legumes, pães, doces e até petiscos. Construído por Receitas da Vó com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 19.9,
    "preco_de": 77,
    "categoria": "gastronomia",
    "tipo": "ebook",
    "vendedor_nome": "Receitas da Vó",
    "vendor_id": "d-019-v",
    "gradient": "from-orange-500 to-red-700",
    "emoji": "🍟",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 2341,
    "total_vendas": 14502,
    "boost": true,
    "created_at": "2026-06-25T01:49:16.000Z"
  },
  {
    "id": "d-020",
    "slug": "curso-marketing-digital-para-iniciantes",
    "titulo": "Curso Marketing Digital para Iniciantes",
    "descricao_curta": "Curso completo para quem está começando do zero no marketing digital brasileiro.",
    "descricao": "Curso completo para quem está começando do zero no marketing digital brasileiro. Construído por Digital Academy com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 97,
    "preco_de": 297,
    "categoria": "marketing",
    "tipo": "curso",
    "vendedor_nome": "Digital Academy",
    "vendor_id": "d-020-v",
    "gradient": "from-sky-500 to-blue-700",
    "emoji": "📱",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 678,
    "total_vendas": 5201,
    "boost": true,
    "created_at": "2026-07-13T01:49:16.000Z"
  },
  {
    "id": "d-021",
    "slug": "edit-pack-capcut-presets-e-transicoes",
    "titulo": "Edit Pack CapCut — Presets e Transições",
    "descricao_curta": "Pacote com 200 presets de CapCut, transições, efeitos e LUTs para vídeos.",
    "descricao": "Pacote com 200 presets de CapCut, transições, efeitos e LUTs para vídeos. Construído por EditPro com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 27,
    "preco_de": 97,
    "categoria": "video",
    "tipo": "pack",
    "vendedor_nome": "EditPro",
    "vendor_id": "d-021-v",
    "gradient": "from-purple-400 to-indigo-600",
    "emoji": "🎥",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 489,
    "total_vendas": 3892,
    "boost": true,
    "created_at": "2026-07-20T01:49:16.000Z"
  },
  {
    "id": "d-022",
    "slug": "gestao-de-tempo-produtividade-maxima",
    "titulo": "Gestão de Tempo Produtividade Máxima",
    "descricao_curta": "Método GTD adaptado para brasileiros: organize sua vida em 30 dias.",
    "descricao": "Método GTD adaptado para brasileiros: organize sua vida em 30 dias. Construído por Foco Total com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 47,
    "preco_de": 197,
    "categoria": "produtividade",
    "tipo": "curso",
    "vendedor_nome": "Foco Total",
    "vendor_id": "d-022-v",
    "gradient": "from-cyan-500 to-teal-700",
    "emoji": "⏱️",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 234,
    "total_vendas": 1542,
    "boost": false,
    "created_at": "2026-06-01T01:49:16.000Z"
  },
  {
    "id": "d-023",
    "slug": "consultoria-instagram-premium-1-1",
    "titulo": "Consultoria Instagram Premium 1:1",
    "descricao_curta": "2 horas de consultoria 1:1 por chamada com análise completa do seu Instagram.",
    "descricao": "2 horas de consultoria 1:1 por chamada com análise completa do seu Instagram. Construído por InstaGuru com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 997,
    "preco_de": 2997,
    "categoria": "servico",
    "tipo": "consultoria",
    "vendedor_nome": "InstaGuru",
    "vendor_id": "d-023-v",
    "gradient": "from-pink-500 to-purple-700",
    "emoji": "📸",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 45,
    "total_vendas": 89,
    "boost": false,
    "created_at": "2026-06-10T01:49:16.000Z"
  },
  {
    "id": "d-024",
    "slug": "pack-icones-minimalistas-ui-2000-icones",
    "titulo": "Pack Ícones Minimalistas UI 2000+ ícones",
    "descricao_curta": "2147 ícones SVG em 3 estilos para sites, apps e projetos — licenciamento comercial.",
    "descricao": "2147 ícones SVG em 3 estilos para sites, apps e projetos — licenciamento comercial. Construído por UI Master com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 47,
    "preco_de": 197,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "UI Master",
    "vendor_id": "d-024-v",
    "gradient": "from-slate-400 to-slate-700",
    "emoji": "✨",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 198,
    "total_vendas": 1203,
    "boost": false,
    "created_at": "2026-06-18T01:49:16.000Z"
  },
  {
    "id": "d-025",
    "slug": "ebook-drenagem-linfatica-em-casa",
    "titulo": "Ebook Drenagem Linfática em Casa",
    "descricao_curta": "Técnicas simples de automassagem para reduzir inchaço em 10 minutos por dia.",
    "descricao": "Técnicas simples de automassagem para reduzir inchaço em 10 minutos por dia. Construído por Ana Massagem com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 17,
    "preco_de": 47,
    "categoria": "saude",
    "tipo": "ebook",
    "vendedor_nome": "Ana Massagem",
    "vendor_id": "d-025-v",
    "gradient": "from-rose-400 to-pink-600",
    "emoji": "💆",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 567,
    "total_vendas": 4203,
    "boost": true,
    "created_at": "2026-06-23T01:49:16.000Z"
  },
  {
    "id": "d-026",
    "slug": "maquiagem-iniciante-curso-completo",
    "titulo": "Maquiagem Iniciante — Curso Completo",
    "descricao_curta": "Aprenda maquiagem do dia a dia, festa, noiva e pele negra em 40 vídeo-aulas.",
    "descricao": "Aprenda maquiagem do dia a dia, festa, noiva e pele negra em 40 vídeo-aulas. Construído por Make Luana com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 77,
    "preco_de": 247,
    "categoria": "beleza",
    "tipo": "curso",
    "vendedor_nome": "Make Luana",
    "vendor_id": "d-026-v",
    "gradient": "from-rose-500 to-red-600",
    "emoji": "💄",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 823,
    "total_vendas": 5432,
    "boost": true,
    "created_at": "2026-07-11T01:49:16.000Z"
  },
  {
    "id": "d-027",
    "slug": "marketing-para-psicologos-atraia-pacientes",
    "titulo": "Marketing para Psicólogos — Atraia Pacientes",
    "descricao_curta": "Como psicólogos conseguem pacientes particulares usando Instagram e Google ético.",
    "descricao": "Como psicólogos conseguem pacientes particulares usando Instagram e Google ético. Construído por Psi Digital com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 147,
    "preco_de": 397,
    "categoria": "profissionais",
    "tipo": "curso",
    "vendedor_nome": "Psi Digital",
    "vendor_id": "d-027-v",
    "gradient": "from-violet-400 to-purple-600",
    "emoji": "🧑‍⚕️",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 145,
    "total_vendas": 892,
    "boost": false,
    "created_at": "2026-06-22T01:49:16.000Z"
  },
  {
    "id": "d-028",
    "slug": "codigo-venda-direta-app-script-de-fechamento",
    "titulo": "Código Venda Direta App — Script de Fechamento",
    "descricao_curta": "42 scripts de fechamento testados em +R$10M em vendas diretas por telefone/WPP.",
    "descricao": "42 scripts de fechamento testados em +R$10M em vendas diretas por telefone/WPP. Construído por Rei do Close com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 97,
    "preco_de": 297,
    "categoria": "vendas",
    "tipo": "script",
    "vendedor_nome": "Rei do Close",
    "vendor_id": "d-028-v",
    "gradient": "from-red-500 to-rose-700",
    "emoji": "🎤",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 312,
    "total_vendas": 2103,
    "boost": false,
    "created_at": "2026-06-10T01:49:16.000Z"
  },
  {
    "id": "d-029",
    "slug": "paginas-de-vendas-elementor-templates",
    "titulo": "Páginas de Vendas Elementor Templates",
    "descricao_curta": "23 templates de página de vendas prontos para WordPress/Elementor — responsivos.",
    "descricao": "23 templates de página de vendas prontos para WordPress/Elementor — responsivos. Construído por WP Ready com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 67,
    "preco_de": 297,
    "categoria": "templates",
    "tipo": "template",
    "vendedor_nome": "WP Ready",
    "vendor_id": "d-029-v",
    "gradient": "from-indigo-400 to-blue-600",
    "emoji": "🌐",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 234,
    "total_vendas": 1621,
    "boost": false,
    "created_at": "2026-06-07T01:49:16.000Z"
  },
  {
    "id": "d-030",
    "slug": "ferramenta-de-calculadora-roi-online",
    "titulo": "Ferramenta de Calculadora ROI Online",
    "descricao_curta": "SaaS web onde seus clientes calculam ROI, ROAS, CAC e LTV automaticamente.",
    "descricao": "SaaS web onde seus clientes calculam ROI, ROAS, CAC e LTV automaticamente. Construído por ROITools com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 47,
    "preco_de": 197,
    "categoria": "software",
    "tipo": "software",
    "vendedor_nome": "ROITools",
    "vendor_id": "d-030-v",
    "gradient": "from-emerald-500 to-green-700",
    "emoji": "🧮",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 187,
    "total_vendas": 987,
    "boost": false,
    "created_at": "2026-06-04T01:49:16.000Z"
  },
  {
    "id": "d-031",
    "slug": "audiobook-o-poder-do-habito-portugues",
    "titulo": "Audiobook — O Poder do Hábito Português",
    "descricao_curta": "Audiobook completo dublado do best-seller com 8h de narração profissional.",
    "descricao": "Audiobook completo dublado do best-seller com 8h de narração profissional. Construído por ÁudioBooks BR com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 29.9,
    "preco_de": 97,
    "categoria": "livros",
    "tipo": "audiobook",
    "vendedor_nome": "ÁudioBooks BR",
    "vendor_id": "d-031-v",
    "gradient": "from-amber-500 to-orange-700",
    "emoji": "🎧",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 345,
    "total_vendas": 2891,
    "boost": false,
    "created_at": "2026-07-13T01:49:16.000Z"
  },
  {
    "id": "d-032",
    "slug": "curso-python-para-analise-de-dados",
    "titulo": "Curso Python para Análise de Dados",
    "descricao_curta": "Do zero ao avançado em Python, Pandas, NumPy, Matplotlib e análise de dados reais.",
    "descricao": "Do zero ao avançado em Python, Pandas, NumPy, Matplotlib e análise de dados reais. Construído por CodeBR com suporte prioritário, atualizações gratuitas e garantia de 7 dias.",
    "preco": 197,
    "preco_de": 597,
    "categoria": "tecnologia",
    "tipo": "curso",
    "vendedor_nome": "CodeBR",
    "vendor_id": "d-032-v",
    "gradient": "from-blue-500 to-cyan-700",
    "emoji": "🐍",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 423,
    "total_vendas": 2341,
    "boost": false,
    "created_at": "2026-05-27T01:49:16.000Z"
  },
  {
    "id": "d-033",
    "slug": "pack-500-prompts-chatgpt-negocios",
    "titulo": "Pack 500 Prompts ChatGPT para Negócios",
    "descricao_curta": "500 prompts testados para copy, reuniões, e-mail, negociação, planilhas e gestão.",
    "descricao": "Coleção de 500 prompts prontos e organizados por categoria (marketing, finanças, RH, vendas, produtividade) para usar no ChatGPT, Gemini ou Claude. Inclui PDF + Notion.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "prompts",
    "tipo": "pack",
    "vendedor_nome": "Prompt Lab BR",
    "vendor_id": "d-033-v",
    "gradient": "from-indigo-500 to-blue-700",
    "emoji": "🧠",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 891,
    "total_vendas": 7620,
    "boost": true,
    "created_at": "2026-07-15T01:49:16.000Z"
  },
  {
    "id": "d-034",
    "slug": "template-canva-instagram-300-criativos",
    "titulo": "Pack 300 Templates Canva Instagram",
    "descricao_curta": "300 templates editáveis para feed, stories, reels e carrosséis em nichos diversos.",
    "descricao": "300 templates profissionais editáveis no Canva: feed, stories, reels, carrosséis, capas de destaque. Atualização mensal gratuita.",
    "preco": 27,
    "preco_de": 197,
    "categoria": "social",
    "tipo": "template",
    "vendedor_nome": "Studio Criativo BR",
    "vendor_id": "d-034-v",
    "gradient": "from-pink-500 to-rose-700",
    "emoji": "🎨",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 1243,
    "total_vendas": 9340,
    "boost": true,
    "created_at": "2026-07-14T01:49:16.000Z"
  },
  {
    "id": "d-035",
    "slug": "ebook-30-ideias-renda-extra-2026",
    "titulo": "E-book: 30 Ideias de Renda Extra para 2026",
    "descricao_curta": "30 métodos testados para ganhar R$1k a R$5k por mês com internet, sem investir.",
    "descricao": "E-book completo com 30 ideias de renda extra validadas para brasileiros, incluindo valores reais, passo a passo e erros comuns.",
    "preco": 9.9,
    "preco_de": 47,
    "categoria": "ebook",
    "tipo": "ebook",
    "vendedor_nome": "Renda Livre",
    "vendor_id": "d-035-v",
    "gradient": "from-emerald-400 to-green-700",
    "emoji": "💰",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 2104,
    "total_vendas": 18240,
    "boost": false,
    "created_at": "2026-07-10T01:49:16.000Z"
  },
  {
    "id": "d-036",
    "slug": "template-notion-dashboard-vida",
    "titulo": "Dashboard Notion Vida Completa",
    "descricao_curta": "Template Notion com finanças, tarefas, hábitos, projetos, CRM, livros e metas.",
    "descricao": "Sistema completo no Notion para organizar sua vida: financeiro, hábitos, projetos, CRM de contatos, leituras, viagens, metas anuais.",
    "preco": 37,
    "preco_de": 147,
    "categoria": "produtividade",
    "tipo": "template",
    "vendedor_nome": "Organiza Digital",
    "vendor_id": "d-036-v",
    "gradient": "from-slate-700 to-slate-900",
    "emoji": "📋",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 567,
    "total_vendas": 4210,
    "boost": false,
    "created_at": "2026-07-08T01:49:16.000Z"
  },
  {
    "id": "d-037",
    "slug": "preset-lightroom-celular-ensolarado",
    "titulo": "25 Presets Lightroom Celular — Ensolarado",
    "descricao_curta": "25 presets profissionais para dar aquele look de praia/verão em suas fotos.",
    "descricao": "Pacote com 25 presets profissionais de Lightroom Mobile (DNG) com tom quente, ensolarado e praiano. Sem necessidade de assinatura.",
    "preco": 14.9,
    "preco_de": 97,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "FotoBR Presets",
    "vendor_id": "d-037-v",
    "gradient": "from-amber-400 to-orange-600",
    "emoji": "📸",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 923,
    "total_vendas": 6780,
    "boost": false,
    "created_at": "2026-07-05T01:49:16.000Z"
  },
  {
    "id": "d-038",
    "slug": "script-reels-virais-100-prontos",
    "titulo": "100 Scripts de Reels Virais Prontos",
    "descricao_curta": "Scripts testados que viralizam em qualquer nicho, com hook e CTA prontos.",
    "descricao": "100 scripts prontos para Reels/TikTok/Shorts organizados por nicho, com hook de 3 segundos, desenvolvimento e CTA matador.",
    "preco": 29.9,
    "preco_de": 197,
    "categoria": "video",
    "tipo": "script",
    "vendedor_nome": "Viralliza",
    "vendor_id": "d-038-v",
    "gradient": "from-red-500 to-orange-500",
    "emoji": "🎬",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 432,
    "total_vendas": 3120,
    "boost": true,
    "created_at": "2026-07-18T01:49:16.000Z"
  },
  {
    "id": "d-039",
    "slug": "curso-edicao-capcut-profissional",
    "titulo": "Curso Edição CapCut do Zero ao Profissional",
    "descricao_curta": "Aprenda a editar shorts e reels que prendem atenção usando apenas o celular.",
    "descricao": "Curso completo de CapCut Mobile e Desktop com transições, efeitos, slow motion, coloração e cortes dinâmicos para vídeos que viralizam.",
    "preco": 47,
    "preco_de": 297,
    "categoria": "video",
    "tipo": "curso",
    "vendedor_nome": "CortaBR",
    "vendor_id": "d-039-v",
    "gradient": "from-purple-600 to-indigo-700",
    "emoji": "✂️",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 678,
    "total_vendas": 2940,
    "boost": false,
    "created_at": "2026-06-28T01:49:16.000Z"
  },
  {
    "id": "d-040",
    "slug": "pack-logos-editaveis-ia-100",
    "titulo": "Pack 100 Logos Editáveis (Gerados com IA)",
    "descricao_curta": "100 logos profissionais editáveis em Canva para pequenos negócios e marcas.",
    "descricao": "100 logos prontos e editáveis para diversos nichos (estética, food, fitness, tech). Formato Canva, SVG e PNG transparente.",
    "preco": 24.9,
    "preco_de": 147,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "LogoLab",
    "vendor_id": "d-040-v",
    "gradient": "from-cyan-500 to-blue-600",
    "emoji": "🔤",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 345,
    "total_vendas": 2180,
    "boost": false,
    "created_at": "2026-07-01T01:49:16.000Z"
  },
  {
    "id": "d-041",
    "slug": "planilha-controle-investimentos-b3",
    "titulo": "Planilha de Controle de Investimentos B3",
    "descricao_curta": "Controle ações, FIIs, CDB, LCI, LCA, dividendos e IR em uma planilha só.",
    "descricao": "Planilha completa para investidores brasileiros: ações, FIIs, BDRs, CDB, LCI/LCA, DCA, dividendos, IR, proventos e análise de carteira.",
    "preco": 39.9,
    "preco_de": 197,
    "categoria": "financas",
    "tipo": "planilha",
    "vendedor_nome": "InvesteAqui",
    "vendor_id": "d-041-v",
    "gradient": "from-teal-500 to-emerald-700",
    "emoji": "📈",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 521,
    "total_vendas": 3890,
    "boost": false,
    "created_at": "2026-06-12T01:49:16.000Z"
  },
  {
    "id": "d-042",
    "slug": "ebook-receitas-lowcarb-90",
    "titulo": "E-book 90 Receitas Low Carb Práticas",
    "descricao_curta": "90 receitas low carb fáceis para o dia a dia, com contagem de calorias.",
    "descricao": "90 receitas low carb testadas e aprovadas: café da manhã, almoço, jantar, sobremesas e lanches. Com contagem de calorias e macros.",
    "preco": 12.9,
    "preco_de": 47,
    "categoria": "saude",
    "tipo": "ebook",
    "vendedor_nome": "Vida Leve",
    "vendor_id": "d-042-v",
    "gradient": "from-lime-400 to-green-600",
    "emoji": "🥗",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 789,
    "total_vendas": 5670,
    "boost": false,
    "created_at": "2026-07-03T01:49:16.000Z"
  },
  {
    "id": "d-043",
    "slug": "template-contrato-prestacao-servicos-editavel",
    "titulo": "Pack 15 Contratos Editáveis (Word/PDF)",
    "descricao_curta": "15 modelos de contrato de prestação de serviços, parceria, NDA e PJ.",
    "descricao": "15 contratos prontos e revisados por advogado: prestação de serviços, parceria, NDA, prestação PJ, confidencialidade, freelancer.",
    "preco": 49.9,
    "preco_de": 297,
    "categoria": "juridico",
    "tipo": "template",
    "vendedor_nome": "Juris Digital",
    "vendor_id": "d-043-v",
    "gradient": "from-stone-500 to-stone-800",
    "emoji": "📜",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 234,
    "total_vendas": 1450,
    "boost": false,
    "created_at": "2026-06-20T01:49:16.000Z"
  },
  {
    "id": "d-044",
    "slug": "mentoria-grupo-mulheres-empreendedoras",
    "titulo": "Mentoria Grupo Elas Vendem (30 dias)",
    "descricao_curta": "Mentoria em grupo de 30 dias para mulheres que querem vender na internet.",
    "descricao": "Mentoria em grupo com encontros ao vivo semanais, grupo VIP no WhatsApp, materiais e suporte diário por 30 dias.",
    "preco": 197,
    "preco_de": 997,
    "categoria": "mentoria",
    "tipo": "mentoria",
    "vendedor_nome": "Carla Empreende",
    "vendor_id": "d-044-v",
    "gradient": "from-rose-400 to-pink-700",
    "emoji": "👩‍💼",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 89,
    "total_vendas": 234,
    "boost": true,
    "created_at": "2026-07-20T01:49:16.000Z"
  },
  {
    "id": "d-045",
    "slug": "template-landing-page-elementor",
    "titulo": "Pack 10 Landing Pages Elementor",
    "descricao_curta": "10 templates de landing page prontos para importar no Elementor/WordPress.",
    "descricao": "10 landing pages profissionais responsivas (captura, vendas, webinar, obrigado) em JSON para importar no Elementor.",
    "preco": 57,
    "preco_de": 247,
    "categoria": "templates",
    "tipo": "template",
    "vendedor_nome": "WebPro BR",
    "vendor_id": "d-045-v",
    "gradient": "from-sky-500 to-indigo-700",
    "emoji": "🖥️",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 312,
    "total_vendas": 1890,
    "boost": false,
    "created_at": "2026-06-08T01:49:16.000Z"
  },
  {
    "id": "d-046",
    "slug": "pack-midias-sociais-barbearia",
    "titulo": "Pack 60 Artes para Barbearia (Canva)",
    "descricao_curta": "60 artes editáveis para barbearias: posts, stories, agendamento e promoções.",
    "descricao": "60 templates de feed e stories prontos para barbearias, com promoções, cortes e horários marcados.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "social",
    "tipo": "template",
    "vendedor_nome": "ArteLocal",
    "vendor_id": "d-046-v",
    "gradient": "from-zinc-600 to-black",
    "emoji": "💈",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 456,
    "total_vendas": 3240,
    "boost": false,
    "created_at": "2026-07-04T01:49:16.000Z"
  },
  {
    "id": "d-047",
    "slug": "curso-marketing-digital-para-iniciantes",
    "titulo": "Marketing Digital para Iniciantes 2026",
    "descricao_curta": "Curso completo do zero para começar no marketing digital sem enrolação.",
    "descricao": "Do zero à primeira venda em 30 dias: tráfego pago, orgânico, copy, funis, esteira de produtos e análise.",
    "preco": 97,
    "preco_de": 497,
    "categoria": "marketing",
    "tipo": "curso",
    "vendedor_nome": "Reis Digital",
    "vendor_id": "d-047-v",
    "gradient": "from-blue-600 to-indigo-800",
    "emoji": "🚀",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 1203,
    "total_vendas": 8970,
    "boost": false,
    "created_at": "2026-06-25T01:49:16.000Z"
  },
  {
    "id": "d-048",
    "slug": "guia-ia-para-pequenos-negocios",
    "titulo": "Guia: IA para Pequenos Negócios",
    "descricao_curta": "Como usar ChatGPT, Midjourney e outras IAs para automatizar seu negócio.",
    "descricao": "Guia prático de 120 páginas mostrando como implementar IA no atendimento, marketing, produção, RH e finanças.",
    "preco": 17.9,
    "preco_de": 97,
    "categoria": "tecnologia",
    "tipo": "ebook",
    "vendedor_nome": "Futuro Negócio",
    "vendor_id": "d-048-v",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "🤖",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 234,
    "total_vendas": 1560,
    "boost": false,
    "created_at": "2026-07-12T01:49:16.000Z"
  },
  {
    "id": "d-049",
    "slug": "template-planilha-calculadora-precificacao",
    "titulo": "Calculadora de Precificação para Serviços",
    "descricao_curta": "Saiba exatamente quanto cobrar por hora, projeto ou freela sem errar.",
    "descricao": "Calculadora automática que considera custos fixos, variáveis, impostos, lucro desejado e valor de mercado.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "planilhas",
    "tipo": "planilha",
    "vendedor_nome": "FreelaPro",
    "vendor_id": "d-049-v",
    "gradient": "from-yellow-400 to-amber-600",
    "emoji": "🧮",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 678,
    "total_vendas": 4560,
    "boost": true,
    "created_at": "2026-07-16T01:49:16.000Z"
  },
  {
    "id": "d-050",
    "slug": "pack-legendas-instagram-1000",
    "titulo": "1000 Legendas Prontas para Instagram",
    "descricao_curta": "Legendas prontas por nicho + hashtags estratégicas para copiar e colar.",
    "descricao": "1000 legendas testadas e organizadas por nicho (moda, fitness, food, negócios, beleza) com hashtags de alto engajamento.",
    "preco": 14.9,
    "preco_de": 97,
    "categoria": "copywriting",
    "tipo": "pack",
    "vendedor_nome": "Legendei",
    "vendor_id": "d-050-v",
    "gradient": "from-fuchsia-500 to-pink-600",
    "emoji": "💬",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 890,
    "total_vendas": 6780,
    "boost": false,
    "created_at": "2026-07-06T01:49:16.000Z"
  },
  {
    "id": "d-051",
    "slug": "template-curriculo-profissional-10",
    "titulo": "Pack 10 Currículos Profissionais Editáveis",
    "descricao_curta": "10 modelos de currículo modernos em Word para passar em ATS.",
    "descricao": "10 templates de currículo modernos, em português, otimizados para ATS das empresas e 100% editáveis no Word.",
    "preco": 9.9,
    "preco_de": 47,
    "categoria": "profissionais",
    "tipo": "template",
    "vendedor_nome": "CarreiraBR",
    "vendor_id": "d-051-v",
    "gradient": "from-slate-500 to-slate-700",
    "emoji": "📄",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 567,
    "total_vendas": 4890,
    "boost": false,
    "created_at": "2026-07-02T01:49:16.000Z"
  },
  {
    "id": "d-052",
    "slug": "aula-make-pele-negra-para-iniciantes",
    "titulo": "Curso de Make para Pele Negra (Iniciantes)",
    "descricao_curta": "Curso online de maquiagem para pele negra com produtos nacionais baratos.",
    "descricao": "Curso completo de maquiagem para pele negra: preparação, base, contorno, olhos, batons, com produtos acessíveis.",
    "preco": 37,
    "preco_de": 197,
    "categoria": "beleza",
    "tipo": "curso",
    "vendedor_nome": "Beleza Afro BR",
    "vendor_id": "d-052-v",
    "gradient": "from-amber-600 to-yellow-900",
    "emoji": "💄",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 234,
    "total_vendas": 1560,
    "boost": false,
    "created_at": "2026-06-30T01:49:16.000Z"
  },
  {
    "id": "d-053",
    "slug": "pack-figurinhas-whatsapp-vendedor",
    "titulo": "200 Figurinhas de Vendedor para WhatsApp",
    "descricao_curta": "Figurinhas prontas para vendas no WhatsApp: urgência, CTA, elogios, objeções.",
    "descricao": "Pacote com 200 figurinhas prontas para vendas no WhatsApp: urgência, oferta, CTA, quebra de objeções, agradecimento.",
    "preco": 7.9,
    "preco_de": 27,
    "categoria": "vendas",
    "tipo": "pack",
    "vendedor_nome": "Vendedor Raiz",
    "vendor_id": "d-053-v",
    "gradient": "from-green-400 to-emerald-600",
    "emoji": "🟢",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 456,
    "total_vendas": 3890,
    "boost": false,
    "created_at": "2026-07-09T01:49:16.000Z"
  },
  {
    "id": "d-054",
    "slug": "template-planner-2027-imprimir",
    "titulo": "Planner 2027 para Imprimir (PDF)",
    "descricao_curta": "Planner completo 2027 com metas, mensal, semanal, diário, hábitos e finanças.",
    "descricao": "Planner 2027 com mais de 200 páginas em PDF pronto para imprimir: anual, mensal, semanal, diário, hábitos, finanças, saúde, leituras.",
    "preco": 14.9,
    "preco_de": 67,
    "categoria": "produtividade",
    "tipo": "template",
    "vendedor_nome": "Organiza Sim",
    "vendor_id": "d-054-v",
    "gradient": "from-rose-300 to-pink-500",
    "emoji": "🗓️",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 678,
    "total_vendas": 5230,
    "boost": false,
    "created_at": "2026-07-17T01:49:16.000Z"
  },
  {
    "id": "d-055",
    "slug": "script-vendas-whatsapp-quebrar-objecoes",
    "titulo": "Scripts de Vendas WhatsApp — Quebrar Objeções",
    "descricao_curta": "100+ scripts prontos para responder objeções mais comuns e fechar vendas.",
    "descricao": "Scripts de WhatsApp testados para responder 'está caro', 'vou pensar', 'tenho que conversar com marido', 'não tenho dinheiro' e mais.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "vendas",
    "tipo": "script",
    "vendedor_nome": "VendaMais",
    "vendor_id": "d-055-v",
    "gradient": "from-green-500 to-teal-700",
    "emoji": "📱",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 890,
    "total_vendas": 6120,
    "boost": true,
    "created_at": "2026-07-19T01:49:16.000Z"
  },
  {
    "id": "d-056",
    "slug": "treino-em-casa-sem-equipamentos-pdf",
    "titulo": "Treino em Casa Sem Equipamentos (PDF)",
    "descricao_curta": "Programa de 8 semanas para emagrecer e ganhar massa sem sair de casa.",
    "descricao": "Programa de treino de 8 semanas para fazer em casa sem equipamentos, com divisão ABCDE, vídeos demonstrativos e dieta inclusa.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "saude",
    "tipo": "ebook",
    "vendedor_nome": "CasaFit",
    "vendor_id": "d-056-v",
    "gradient": "from-red-500 to-rose-700",
    "emoji": "🏋️",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 567,
    "total_vendas": 4340,
    "boost": false,
    "created_at": "2026-06-18T01:49:16.000Z"
  },
  {
    "id": "d-057",
    "slug": "template-cardapio-digital-qrcode",
    "titulo": "Template Cardápio Digital QR Code (Canva)",
    "descricao_curta": "Cardápio digital editável para restaurantes, lanchonetes e cafés.",
    "descricao": "Cardápio digital profissional editável no Canva + QR code gerado automaticamente para restaurantes, lanchonetes e food service.",
    "preco": 24.9,
    "preco_de": 97,
    "categoria": "gastronomia",
    "tipo": "template",
    "vendedor_nome": "Food Design BR",
    "vendor_id": "d-057-v",
    "gradient": "from-orange-500 to-red-600",
    "emoji": "🍽️",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 234,
    "total_vendas": 1890,
    "boost": false,
    "created_at": "2026-07-07T01:49:16.000Z"
  },
  {
    "id": "d-058",
    "slug": "pack-kdp-interior-colorir",
    "titulo": "50 Interiores Livro de Colorir KDP (PDF)",
    "descricao_curta": "50 interiores prontos para publicar livros de colorir na Amazon KDP.",
    "descricao": "50 interiores de livros de colorir em PDF prontos para Amazon KDP (8.5x11 polegadas), com temáticas diversas para adultos e crianças.",
    "preco": 29.9,
    "preco_de": 197,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "KDP BR",
    "vendor_id": "d-058-v",
    "gradient": "from-violet-400 to-indigo-600",
    "emoji": "🎨",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 345,
    "total_vendas": 2100,
    "boost": false,
    "created_at": "2026-06-15T01:49:16.000Z"
  }
];
