// Produtos no estilo "GGMax" — 50 produtos digitais reais (keys, gift cards, assinaturas, cursos, packs)
// Vendedores separados por categoria (incluindo KIYVO Oficial para produtos padrão)

export interface GGVendor {
  id: string
  nome: string
  categoria: string
  verificado: boolean
}

export interface GGProduct {
  id: string
  slug: string
  titulo: string
  descricao_curta: string
  descricao: string
  preco: number
  preco_de: number
  categoria: string
  tipo: string
  vendedor_nome: string
  vendor_id: string
  gradient: string
  emoji: string
  imagem_capa: null
  rating: number
  total_reviews: number
  total_vendas: number
  boost: boolean
  verificado: boolean
  created_at: string
  entrega_automatica: boolean
  garantia_dias: number
}

export const GG_VENDEDORES: GGVendor[] = [
  {
    "id": "kiyvo-oficial",
    "nome": "KIYVO Oficial",
    "categoria": "padrao",
    "verificado": true
  },
  {
    "id": "keysbr-digital",
    "nome": "KeysBR Digital",
    "categoria": "software",
    "verificado": true
  },
  {
    "id": "streaming-plus",
    "nome": "Streaming Plus",
    "categoria": "streaming",
    "verificado": true
  },
  {
    "id": "prodigital-br",
    "nome": "Pro Digital BR",
    "categoria": "ferramentas",
    "verificado": true
  },
  {
    "id": "gamekey-store",
    "nome": "GameKey Store",
    "categoria": "jogos",
    "verificado": false
  },
  {
    "id": "planilhas-chefe",
    "nome": "Planilhas do Chefe",
    "categoria": "negocios",
    "verificado": true
  },
  {
    "id": "cursos-lucrativos",
    "nome": "Cursos Lucrativos",
    "categoria": "cursos",
    "verificado": false
  },
  {
    "id": "design-pack",
    "nome": "Design Pack BR",
    "categoria": "design",
    "verificado": true
  },
  {
    "id": "gift-cards-br",
    "nome": "Gift Cards BR",
    "categoria": "giftcards",
    "verificado": true
  }
];

export const GG_PRODUCTS: GGProduct[] = [
  {
    "id": "gg-001",
    "slug": "windows-11-pro-vitalicio-chave-original",
    "titulo": "Windows 11 Pro Vitalício (Chave Original)",
    "descricao_curta": "Ative o Windows 11 Pro permanentemente. Chave original 32/64 bits, envio imediato por email.",
    "descricao": "Ative o Windows 11 Pro permanentemente. Chave original 32/64 bits, envio imediato por email. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 49.9,
    "preco_de": 799,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "🪟",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 417,
    "total_vendas": 3156,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-03T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-002",
    "slug": "windows-10-pro-vitalicio",
    "titulo": "Windows 10 Pro Vitalício",
    "descricao_curta": "Chave original Windows 10 Pro, licença permanente, atualizações inclusas.",
    "descricao": "Chave original Windows 10 Pro, licença permanente, atualizações inclusas. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 39.9,
    "preco_de": 599,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "🪟",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 531,
    "total_vendas": 7970,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-07T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-003",
    "slug": "microsoft-office-365-vitalicio-5-dispositivos",
    "titulo": "Microsoft Office 365 Vitalício (5 dispositivos)",
    "descricao_curta": "Word, Excel, PowerPoint, Outlook e OneDrive com 1TB. Conta com email e senha, vitalício.",
    "descricao": "Word, Excel, PowerPoint, Outlook e OneDrive com 1TB. Conta com email e senha, vitalício. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 79.9,
    "preco_de": 1499,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "📄",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 97,
    "total_vendas": 9058,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-10T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-004",
    "slug": "office-2021-pro-plus-vitalicio",
    "titulo": "Office 2021 Pro Plus Vitalício",
    "descricao_curta": "Office 2021 Professional Plus — licença perpétua para 1 PC. Ativação online.",
    "descricao": "Office 2021 Professional Plus — licença perpétua para 1 PC. Ativação online. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 59.9,
    "preco_de": 1099,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "📊",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 811,
    "total_vendas": 1839,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-02T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-005",
    "slug": "antivirus-kaspersky-total-security-1-ano",
    "titulo": "Antivírus Kaspersky Total Security 1 ano",
    "descricao_curta": "Proteção completa para 1 dispositivo por 12 meses. Licença original Kaspersky.",
    "descricao": "Proteção completa para 1 dispositivo por 12 meses. Licença original Kaspersky. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 29.9,
    "preco_de": 129,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "🛡️",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 687,
    "total_vendas": 6211,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-15T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-006",
    "slug": "netflix-premium-4k-30-dias",
    "titulo": "Netflix Premium 4K (30 dias)",
    "descricao_curta": "Tela Ultra HD 4K + 4 telas simultâneas. Acesso por 30 dias.",
    "descricao": "Tela Ultra HD 4K + 4 telas simultâneas. Acesso por 30 dias. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 19.9,
    "preco_de": 55.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "🎬",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 750,
    "total_vendas": 8988,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-08T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-007",
    "slug": "spotify-premium-individual-30-dias",
    "titulo": "Spotify Premium Individual (30 dias)",
    "descricao_curta": "Conta premium individual sem anúncios, modo offline, qualidade alta.",
    "descricao": "Conta premium individual sem anúncios, modo offline, qualidade alta. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 9.9,
    "preco_de": 21.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "🎵",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 832,
    "total_vendas": 4312,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-13T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-008",
    "slug": "gift-card-steam-r-50",
    "titulo": "Gift Card Steam R$50",
    "descricao_curta": "Código para adicionar R$50 na carteira Steam. Entrega instantânea.",
    "descricao": "Código para adicionar R$50 na carteira Steam. Entrega instantânea. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 47.9,
    "preco_de": 50,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "💳",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 1126,
    "total_vendas": 8336,
    "boost": true,
    "verificado": true,
    "created_at": "2026-06-24T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-009",
    "slug": "gift-card-ifood-r-100",
    "titulo": "Gift Card iFood R$100",
    "descricao_curta": "R$100 em créditos para usar no iFood. Válido em todo o Brasil.",
    "descricao": "R$100 em créditos para usar no iFood. Válido em todo o Brasil. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 92.9,
    "preco_de": 100,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "🍔",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 120,
    "total_vendas": 2163,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-06T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-010",
    "slug": "chatgpt-plus-gpt-4-acesso-1-mes",
    "titulo": "ChatGPT Plus (GPT-4) — Acesso 1 mês",
    "descricao_curta": "Conta ChatGPT Plus com acesso ao GPT-4, DALL-E 3, Advanced Data Analysis. Renovação garantida.",
    "descricao": "Conta ChatGPT Plus com acesso ao GPT-4, DALL-E 3, Advanced Data Analysis. Renovação garantida. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 49.9,
    "preco_de": 120,
    "categoria": "ferramentas",
    "tipo": "assinatura",
    "vendedor_nome": "KIYVO Oficial",
    "vendor_id": "kiyvo-oficial",
    "gradient": "from-brand-500 to-brand-700",
    "emoji": "🤖",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 147,
    "total_vendas": 8691,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-22T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-011",
    "slug": "windows-11-home-vitalicio",
    "titulo": "Windows 11 Home Vitalício",
    "descricao_curta": "Chave original do Windows 11 Home. Ativação online garantida.",
    "descricao": "Chave original do Windows 11 Home. Ativação online garantida. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 29.9,
    "preco_de": 399,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KeysBR Digital",
    "vendor_id": "keysbr-digital",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "🪟",
    "imagem_capa": null,
    "rating": 4.3,
    "total_reviews": 1154,
    "total_vendas": 8469,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-22T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-012",
    "slug": "adobe-creative-cloud-1-mes-todos-os-apps",
    "titulo": "Adobe Creative Cloud 1 mês (todos os apps)",
    "descricao_curta": "Photoshop, Illustrator, Premiere, After Effects, InDesign e mais. Conta logada, 30 dias.",
    "descricao": "Photoshop, Illustrator, Premiere, After Effects, InDesign e mais. Conta logada, 30 dias. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 49.9,
    "preco_de": 140,
    "categoria": "software",
    "tipo": "assinatura",
    "vendedor_nome": "KeysBR Digital",
    "vendor_id": "keysbr-digital",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "🎨",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 1168,
    "total_vendas": 5789,
    "boost": false,
    "verificado": true,
    "created_at": "2026-06-25T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-013",
    "slug": "autocad-2024-2025-licenca-educacional",
    "titulo": "AutoCAD 2024/2025 Licença Educacional",
    "descricao_curta": "Autodesk AutoCAD para Windows/Mac — licença educacional válida por 1 ano.",
    "descricao": "Autodesk AutoCAD para Windows/Mac — licença educacional válida por 1 ano. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 89.9,
    "preco_de": 900,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KeysBR Digital",
    "vendor_id": "keysbr-digital",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "📐",
    "imagem_capa": null,
    "rating": 4.4,
    "total_reviews": 50,
    "total_vendas": 7945,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-12T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-014",
    "slug": "coreldraw-graphics-suite-2024",
    "titulo": "CorelDRAW Graphics Suite 2024",
    "descricao_curta": "CorelDRAW, PHOTO-PAINT e Font Manager. Licença permanente para Windows.",
    "descricao": "CorelDRAW, PHOTO-PAINT e Font Manager. Licença permanente para Windows. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 69.9,
    "preco_de": 1300,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KeysBR Digital",
    "vendor_id": "keysbr-digital",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "🖌️",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 700,
    "total_vendas": 1210,
    "boost": false,
    "verificado": true,
    "created_at": "2026-06-24T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-015",
    "slug": "photoshop-cc-2024-licenca-vitalicia",
    "titulo": "Photoshop CC 2024 Licença Vitalícia",
    "descricao_curta": "Adobe Photoshop 2024 com atualizações — licença permanente. Sem assinatura mensal.",
    "descricao": "Adobe Photoshop 2024 com atualizações — licença permanente. Sem assinatura mensal. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 59.9,
    "preco_de": 1200,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KeysBR Digital",
    "vendor_id": "keysbr-digital",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "🖼️",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 500,
    "total_vendas": 6706,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-12T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-016",
    "slug": "microsoft-365-family-6-usuarios-1-ano",
    "titulo": "Microsoft 365 Family 6 usuários (1 ano)",
    "descricao_curta": "Office 365 Family para 6 pessoas, 1TB OneDrive cada, 12 meses.",
    "descricao": "Office 365 Family para 6 pessoas, 1TB OneDrive cada, 12 meses. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 129.9,
    "preco_de": 359,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KeysBR Digital",
    "vendor_id": "keysbr-digital",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "👨‍👩‍👧‍👦",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 710,
    "total_vendas": 7528,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-22T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-017",
    "slug": "windows-server-2022-standard",
    "titulo": "Windows Server 2022 Standard",
    "descricao_curta": "Licença Windows Server 2022 Standard — vitalícia para empresas.",
    "descricao": "Licença Windows Server 2022 Standard — vitalícia para empresas. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 199.9,
    "preco_de": 3500,
    "categoria": "software",
    "tipo": "licenca",
    "vendedor_nome": "KeysBR Digital",
    "vendor_id": "keysbr-digital",
    "gradient": "from-blue-500 to-indigo-700",
    "emoji": "🖥️",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 511,
    "total_vendas": 3338,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-10T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-018",
    "slug": "disney-premium-4k-30-dias",
    "titulo": "Disney+ Premium 4K 30 dias",
    "descricao_curta": "Disney+ com Star+, 4 telas simultâneas, qualidade 4K UHD.",
    "descricao": "Disney+ com Star+, 4 telas simultâneas, qualidade 4K UHD. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 17.9,
    "preco_de": 37.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "Streaming Plus",
    "vendor_id": "streaming-plus",
    "gradient": "from-rose-500 to-pink-700",
    "emoji": "🐭",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 969,
    "total_vendas": 1306,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-20T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-019",
    "slug": "prime-video-30-dias",
    "titulo": "Prime Video 30 dias",
    "descricao_curta": "Amazon Prime Video em 4K, entrega Prime incluso. 1 mês de acesso.",
    "descricao": "Amazon Prime Video em 4K, entrega Prime incluso. 1 mês de acesso. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 9.9,
    "preco_de": 19.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "Streaming Plus",
    "vendor_id": "streaming-plus",
    "gradient": "from-rose-500 to-pink-700",
    "emoji": "📦",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 908,
    "total_vendas": 7859,
    "boost": true,
    "verificado": true,
    "created_at": "2026-06-30T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-020",
    "slug": "hbo-max-max-premium-30-dias",
    "titulo": "HBO Max (Max) Premium 30 dias",
    "descricao_curta": "Max (antigo HBO) com todo o catálogo Warner, HBO e DC. Qualidade Full HD.",
    "descricao": "Max (antigo HBO) com todo o catálogo Warner, HBO e DC. Qualidade Full HD. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 14.9,
    "preco_de": 39.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "Streaming Plus",
    "vendor_id": "streaming-plus",
    "gradient": "from-rose-500 to-pink-700",
    "emoji": "🍿",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 398,
    "total_vendas": 5779,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-11T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-021",
    "slug": "globoplay-canais-ao-vivo-30-dias",
    "titulo": "Globoplay + Canais ao Vivo 30 dias",
    "descricao_curta": "Globoplay com novelas, séries, BBB e canais ao vivo por 30 dias.",
    "descricao": "Globoplay com novelas, séries, BBB e canais ao vivo por 30 dias. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 15.9,
    "preco_de": 49.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "Streaming Plus",
    "vendor_id": "streaming-plus",
    "gradient": "from-rose-500 to-pink-700",
    "emoji": "📺",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 238,
    "total_vendas": 6469,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-19T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-022",
    "slug": "youtube-premium-30-dias",
    "titulo": "YouTube Premium 30 dias",
    "descricao_curta": "YouTube sem anúncios, YouTube Music, reprodução em segundo plano.",
    "descricao": "YouTube sem anúncios, YouTube Music, reprodução em segundo plano. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 12.9,
    "preco_de": 24.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "Streaming Plus",
    "vendor_id": "streaming-plus",
    "gradient": "from-rose-500 to-pink-700",
    "emoji": "▶️",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 461,
    "total_vendas": 881,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-03T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-023",
    "slug": "paramount-30-dias",
    "titulo": "Paramount+ 30 dias",
    "descricao_curta": "Paramount+ com futebol, séries e filmes da Paramount. Acesso total.",
    "descricao": "Paramount+ com futebol, séries e filmes da Paramount. Acesso total. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 9.9,
    "preco_de": 19.9,
    "categoria": "streaming",
    "tipo": "assinatura",
    "vendedor_nome": "Streaming Plus",
    "vendor_id": "streaming-plus",
    "gradient": "from-rose-500 to-pink-700",
    "emoji": "🎞️",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 351,
    "total_vendas": 5518,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-18T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-024",
    "slug": "canva-pro-vitalicio-equipe",
    "titulo": "Canva Pro Vitalício (Equipe)",
    "descricao_curta": "Canva Pro com templates premium, remover fundo, agendamento de posts. Vitalício.",
    "descricao": "Canva Pro com templates premium, remover fundo, agendamento de posts. Vitalício. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 39.9,
    "preco_de": 360,
    "categoria": "ferramentas",
    "tipo": "assinatura",
    "vendedor_nome": "Pro Digital BR",
    "vendor_id": "prodigital-br",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "🎨",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 1228,
    "total_vendas": 9325,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-07T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-025",
    "slug": "grammarly-premium-1-mes",
    "titulo": "Grammarly Premium 1 mês",
    "descricao_curta": "Correção gramatical avançada em inglês, detecção de plágio, sugestões de tom.",
    "descricao": "Correção gramatical avançada em inglês, detecção de plágio, sugestões de tom. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 24.9,
    "preco_de": 60,
    "categoria": "ferramentas",
    "tipo": "assinatura",
    "vendedor_nome": "Pro Digital BR",
    "vendor_id": "prodigital-br",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "✍️",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 634,
    "total_vendas": 4030,
    "boost": false,
    "verificado": true,
    "created_at": "2026-06-29T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-026",
    "slug": "notion-ai-plus-1-ano",
    "titulo": "Notion AI Plus 1 ano",
    "descricao_curta": "Notion Plus com AI integrado, blocos ilimitados, upload de arquivos grandes.",
    "descricao": "Notion Plus com AI integrado, blocos ilimitados, upload de arquivos grandes. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 49.9,
    "preco_de": 480,
    "categoria": "ferramentas",
    "tipo": "assinatura",
    "vendedor_nome": "Pro Digital BR",
    "vendor_id": "prodigital-br",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "📝",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 584,
    "total_vendas": 2507,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-16T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-027",
    "slug": "midjourney-standard-1-mes-30h-fast",
    "titulo": "Midjourney Standard 1 mês (30h fast)",
    "descricao_curta": "Acesso ao Midjourney Standard com 15h de geração rápida por mês. Convite em servidor.",
    "descricao": "Acesso ao Midjourney Standard com 15h de geração rápida por mês. Convite em servidor. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 69.9,
    "preco_de": 190,
    "categoria": "ferramentas",
    "tipo": "assinatura",
    "vendedor_nome": "Pro Digital BR",
    "vendor_id": "prodigital-br",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "🎨",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 621,
    "total_vendas": 1443,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-13T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-028",
    "slug": "capcut-pro-1-mes-todos-os-efeitos",
    "titulo": "CapCut Pro 1 mês (todos os efeitos)",
    "descricao_curta": "CapCut Pro com templates premium, efeitos exclusivos e exportação em 4K.",
    "descricao": "CapCut Pro com templates premium, efeitos exclusivos e exportação em 4K. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 19.9,
    "preco_de": 49.9,
    "categoria": "ferramentas",
    "tipo": "assinatura",
    "vendedor_nome": "Pro Digital BR",
    "vendor_id": "prodigital-br",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "✂️",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 866,
    "total_vendas": 8945,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-02T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-029",
    "slug": "linkedin-premium-career-1-mes",
    "titulo": "LinkedIn Premium Career 1 mês",
    "descricao_curta": "LinkedIn Premium para carreira: ver quem viu seu perfil, InMail ilimitado, destaque.",
    "descricao": "LinkedIn Premium para carreira: ver quem viu seu perfil, InMail ilimitado, destaque. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 39.9,
    "preco_de": 79.9,
    "categoria": "ferramentas",
    "tipo": "assinatura",
    "vendedor_nome": "Pro Digital BR",
    "vendor_id": "prodigital-br",
    "gradient": "from-violet-500 to-purple-700",
    "emoji": "💼",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 202,
    "total_vendas": 5335,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-12T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-030",
    "slug": "steam-key-gta-v-premium-edition",
    "titulo": "Steam Key — GTA V Premium Edition",
    "descricao_curta": "Chave Steam do Grand Theft Auto V Premium Online Edition. Ativação global.",
    "descricao": "Chave Steam do Grand Theft Auto V Premium Online Edition. Ativação global. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 39.9,
    "preco_de": 99,
    "categoria": "jogos",
    "tipo": "game",
    "vendedor_nome": "GameKey Store",
    "vendor_id": "gamekey-store",
    "gradient": "from-orange-500 to-red-600",
    "emoji": "🚗",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 495,
    "total_vendas": 3857,
    "boost": false,
    "verificado": false,
    "created_at": "2026-07-04T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-031",
    "slug": "gift-card-playstation-store-r-100",
    "titulo": "Gift Card PlayStation Store R$100",
    "descricao_curta": "R$100 em créditos para PSN (PS4/PS5). Entrega imediata.",
    "descricao": "R$100 em créditos para PSN (PS4/PS5). Entrega imediata. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 94.9,
    "preco_de": 100,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "GameKey Store",
    "vendor_id": "gamekey-store",
    "gradient": "from-orange-500 to-red-600",
    "emoji": "🎮",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 682,
    "total_vendas": 1193,
    "boost": false,
    "verificado": false,
    "created_at": "2026-06-30T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-032",
    "slug": "gift-card-xbox-r-100",
    "titulo": "Gift Card Xbox R$100",
    "descricao_curta": "Crédito de R$100 para Xbox Store (Xbox One, Series S/X).",
    "descricao": "Crédito de R$100 para Xbox Store (Xbox One, Series S/X). Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 94.9,
    "preco_de": 100,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "GameKey Store",
    "vendor_id": "gamekey-store",
    "gradient": "from-orange-500 to-red-600",
    "emoji": "🟢",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 265,
    "total_vendas": 5243,
    "boost": false,
    "verificado": false,
    "created_at": "2026-07-09T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-033",
    "slug": "steam-key-counter-strike-2-prime-status",
    "titulo": "Steam Key — Counter-Strike 2 Prime Status",
    "descricao_curta": "Status Prime do CS2: partidas ranqueadas, drops exclusivos, sem trapaceiros.",
    "descricao": "Status Prime do CS2: partidas ranqueadas, drops exclusivos, sem trapaceiros. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 59.9,
    "preco_de": 99.9,
    "categoria": "jogos",
    "tipo": "game",
    "vendedor_nome": "GameKey Store",
    "vendor_id": "gamekey-store",
    "gradient": "from-orange-500 to-red-600",
    "emoji": "🔫",
    "imagem_capa": null,
    "rating": 4.4,
    "total_reviews": 673,
    "total_vendas": 4072,
    "boost": false,
    "verificado": false,
    "created_at": "2026-07-19T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-034",
    "slug": "planilha-fluxo-de-caixa-empresarial",
    "titulo": "Planilha Fluxo de Caixa Empresarial",
    "descricao_curta": "Planilha Excel/Google Sheets completa para controle financeiro de MEI/pequenas empresas. Gráficos automáticos.",
    "descricao": "Planilha Excel/Google Sheets completa para controle financeiro de MEI/pequenas empresas. Gráficos automáticos. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "negocios",
    "tipo": "planilha",
    "vendedor_nome": "Planilhas do Chefe",
    "vendor_id": "planilhas-chefe",
    "gradient": "from-emerald-500 to-teal-700",
    "emoji": "💰",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 129,
    "total_vendas": 8712,
    "boost": true,
    "verificado": true,
    "created_at": "2026-06-26T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-035",
    "slug": "planilha-de-controle-de-gastos-pessoal",
    "titulo": "Planilha de Controle de Gastos Pessoal",
    "descricao_curta": "Controle de orçamento doméstico com categorias, metas e dashboard. Fórmula 50/30/20 inclusa.",
    "descricao": "Controle de orçamento doméstico com categorias, metas e dashboard. Fórmula 50/30/20 inclusa. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 9.9,
    "preco_de": 47,
    "categoria": "negocios",
    "tipo": "planilha",
    "vendedor_nome": "Planilhas do Chefe",
    "vendor_id": "planilhas-chefe",
    "gradient": "from-emerald-500 to-teal-700",
    "emoji": "💵",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 298,
    "total_vendas": 5173,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-19T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-036",
    "slug": "planilha-de-calculadora-roi-anuncios",
    "titulo": "Planilha de Calculadora ROI Anúncios",
    "descricao_curta": "Calcule CAC, CPA, ROAS, LTV e lucro real das suas campanhas de tráfego pago.",
    "descricao": "Calcule CAC, CPA, ROAS, LTV e lucro real das suas campanhas de tráfego pago. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 24.9,
    "preco_de": 97,
    "categoria": "negocios",
    "tipo": "planilha",
    "vendedor_nome": "Planilhas do Chefe",
    "vendor_id": "planilhas-chefe",
    "gradient": "from-emerald-500 to-teal-700",
    "emoji": "📈",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 68,
    "total_vendas": 7538,
    "boost": false,
    "verificado": true,
    "created_at": "2026-06-30T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-037",
    "slug": "modelo-de-contrato-de-prestacao-de-servicos-word",
    "titulo": "Modelo de Contrato de Prestação de Serviços (Word)",
    "descricao_curta": "Template editável de contrato de prestação de serviços LGPD-compliant com 12 cláusulas.",
    "descricao": "Template editável de contrato de prestação de serviços LGPD-compliant com 12 cláusulas. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 14.9,
    "preco_de": 97,
    "categoria": "negocios",
    "tipo": "template",
    "vendedor_nome": "Planilhas do Chefe",
    "vendor_id": "planilhas-chefe",
    "gradient": "from-emerald-500 to-teal-700",
    "emoji": "📋",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 610,
    "total_vendas": 5285,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-21T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-038",
    "slug": "curso-de-marketing-digital-do-zero",
    "titulo": "Curso de Marketing Digital do Zero",
    "descricao_curta": "40 vídeo-aulas ensinando tráfego, copy, funil e lançamento. Acesso vitalício.",
    "descricao": "40 vídeo-aulas ensinando tráfego, copy, funil e lançamento. Acesso vitalício. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 29.9,
    "preco_de": 297,
    "categoria": "cursos",
    "tipo": "curso",
    "vendedor_nome": "Cursos Lucrativos",
    "vendor_id": "cursos-lucrativos",
    "gradient": "from-amber-500 to-orange-600",
    "emoji": "📣",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 149,
    "total_vendas": 373,
    "boost": false,
    "verificado": false,
    "created_at": "2026-07-03T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-039",
    "slug": "curso-excel-completo-basico-ao-avancado",
    "titulo": "Curso Excel Completo (básico ao avançado)",
    "descricao_curta": "Do zero ao avançado em Excel: fórmulas, tabela dinâmica, macros, VBA e dashboards.",
    "descricao": "Do zero ao avançado em Excel: fórmulas, tabela dinâmica, macros, VBA e dashboards. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 24.9,
    "preco_de": 197,
    "categoria": "cursos",
    "tipo": "curso",
    "vendedor_nome": "Cursos Lucrativos",
    "vendor_id": "cursos-lucrativos",
    "gradient": "from-amber-500 to-orange-600",
    "emoji": "📊",
    "imagem_capa": null,
    "rating": 4.4,
    "total_reviews": 1057,
    "total_vendas": 953,
    "boost": false,
    "verificado": false,
    "created_at": "2026-06-25T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-040",
    "slug": "curso-renda-extra-com-ia-em-7-dias",
    "titulo": "Curso Renda Extra com IA em 7 dias",
    "descricao_curta": "Aprenda a usar ChatGPT e Midjourney para oferecer serviços e ganhar de R$1k a R$5k/mês.",
    "descricao": "Aprenda a usar ChatGPT e Midjourney para oferecer serviços e ganhar de R$1k a R$5k/mês. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 19.9,
    "preco_de": 97,
    "categoria": "cursos",
    "tipo": "curso",
    "vendedor_nome": "Cursos Lucrativos",
    "vendor_id": "cursos-lucrativos",
    "gradient": "from-amber-500 to-orange-600",
    "emoji": "🤖",
    "imagem_capa": null,
    "rating": 4.7,
    "total_reviews": 388,
    "total_vendas": 4773,
    "boost": true,
    "verificado": false,
    "created_at": "2026-06-29T02:44:28.780Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-041",
    "slug": "pack-500-templates-canva-para-redes-sociais",
    "titulo": "Pack 500 Templates Canva para Redes Sociais",
    "descricao_curta": "500 templates prontos para Instagram, Reels e Stories — 100% editáveis.",
    "descricao": "500 templates prontos para Instagram, Reels e Stories — 100% editáveis. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 14.9,
    "preco_de": 197,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "Cursos Lucrativos",
    "vendor_id": "cursos-lucrativos",
    "gradient": "from-amber-500 to-orange-600",
    "emoji": "📱",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 708,
    "total_vendas": 9520,
    "boost": true,
    "verificado": false,
    "created_at": "2026-07-01T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-042",
    "slug": "pack-10-000-presets-lightroom-mobile-desktop",
    "titulo": "Pack 10.000 Presets Lightroom (Mobile/Desktop)",
    "descricao_curta": "10 mil presets para Lightroom de fotografia: ensaio, casamento, urbano, natureza, dark.",
    "descricao": "10 mil presets para Lightroom de fotografia: ensaio, casamento, urbano, natureza, dark. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 17.9,
    "preco_de": 147,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "Design Pack BR",
    "vendor_id": "design-pack",
    "gradient": "from-fuchsia-500 to-pink-700",
    "emoji": "📷",
    "imagem_capa": null,
    "rating": 4.4,
    "total_reviews": 1006,
    "total_vendas": 4161,
    "boost": true,
    "verificado": true,
    "created_at": "2026-06-30T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-043",
    "slug": "bundle-5-000-icones-svg-premium",
    "titulo": "Bundle 5.000 Ícones SVG Premium",
    "descricao_curta": "5 mil ícones em SVG em 3 estilos para sites e apps. Licença comercial.",
    "descricao": "5 mil ícones em SVG em 3 estilos para sites e apps. Licença comercial. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 12.9,
    "preco_de": 97,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "Design Pack BR",
    "vendor_id": "design-pack",
    "gradient": "from-fuchsia-500 to-pink-700",
    "emoji": "✨",
    "imagem_capa": null,
    "rating": 4.6,
    "total_reviews": 770,
    "total_vendas": 3541,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-09T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-044",
    "slug": "pack-2-000-fontes-profissionais-windows-mac",
    "titulo": "Pack 2.000 Fontes Profissionais (Windows/Mac)",
    "descricao_curta": "2 mil fontes premium com licença comercial para designers. Inclui serifa, sans, script, display.",
    "descricao": "2 mil fontes premium com licença comercial para designers. Inclui serifa, sans, script, display. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 14.9,
    "preco_de": 197,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "Design Pack BR",
    "vendor_id": "design-pack",
    "gradient": "from-fuchsia-500 to-pink-700",
    "emoji": "🔤",
    "imagem_capa": null,
    "rating": 5,
    "total_reviews": 163,
    "total_vendas": 7208,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-15T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-045",
    "slug": "mockups-profissionais-500-cenas",
    "titulo": "Mockups Profissionais — 500 cenas",
    "descricao_curta": "500 mockups PSD de camisetas, canecas, telas, embalagens e livros para portfólio.",
    "descricao": "500 mockups PSD de camisetas, canecas, telas, embalagens e livros para portfólio. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 19.9,
    "preco_de": 197,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "Design Pack BR",
    "vendor_id": "design-pack",
    "gradient": "from-fuchsia-500 to-pink-700",
    "emoji": "🖼️",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 81,
    "total_vendas": 686,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-01T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-046",
    "slug": "presets-luts-para-videos-4k-50-estilos",
    "titulo": "Presets LUTs para Vídeos 4K (50 estilos)",
    "descricao_curta": "50 LUTs profissionais de correção de cor para Premiere, DaVinci Resolve e CapCut.",
    "descricao": "50 LUTs profissionais de correção de cor para Premiere, DaVinci Resolve e CapCut. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 12.9,
    "preco_de": 97,
    "categoria": "design",
    "tipo": "pack",
    "vendedor_nome": "Design Pack BR",
    "vendor_id": "design-pack",
    "gradient": "from-fuchsia-500 to-pink-700",
    "emoji": "🎞️",
    "imagem_capa": null,
    "rating": 4.3,
    "total_reviews": 619,
    "total_vendas": 6223,
    "boost": true,
    "verificado": true,
    "created_at": "2026-07-02T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-047",
    "slug": "gift-card-uber-r-50",
    "titulo": "Gift Card Uber R$50",
    "descricao_curta": "Crédito R$50 para Uber ou Uber Eats em todo o Brasil.",
    "descricao": "Crédito R$50 para Uber ou Uber Eats em todo o Brasil. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 45.9,
    "preco_de": 50,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "Gift Cards BR",
    "vendor_id": "gift-cards-br",
    "gradient": "from-lime-500 to-green-700",
    "emoji": "🚗",
    "imagem_capa": null,
    "rating": 4.5,
    "total_reviews": 293,
    "total_vendas": 5382,
    "boost": false,
    "verificado": true,
    "created_at": "2026-06-28T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-048",
    "slug": "gift-card-google-play-r-50",
    "titulo": "Gift Card Google Play R$50",
    "descricao_curta": "R$50 em créditos Google Play para apps, jogos e assinaturas.",
    "descricao": "R$50 em créditos Google Play para apps, jogos e assinaturas. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 47.9,
    "preco_de": 50,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "Gift Cards BR",
    "vendor_id": "gift-cards-br",
    "gradient": "from-lime-500 to-green-700",
    "emoji": "🤖",
    "imagem_capa": null,
    "rating": 4.9,
    "total_reviews": 1062,
    "total_vendas": 9026,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-04T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-049",
    "slug": "gift-card-app-store-r-50",
    "titulo": "Gift Card App Store R$50",
    "descricao_curta": "R$50 em créditos Apple ID para App Store, iCloud e Apple Music.",
    "descricao": "R$50 em créditos Apple ID para App Store, iCloud e Apple Music. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 47.9,
    "preco_de": 50,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "Gift Cards BR",
    "vendor_id": "gift-cards-br",
    "gradient": "from-lime-500 to-green-700",
    "emoji": "🍎",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 286,
    "total_vendas": 326,
    "boost": false,
    "verificado": true,
    "created_at": "2026-06-24T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  },
  {
    "id": "gg-050",
    "slug": "gift-card-amazon-r-100",
    "titulo": "Gift Card Amazon R$100",
    "descricao_curta": "Crédito R$100 para compras na Amazon Brasil. Não expira.",
    "descricao": "Crédito R$100 para compras na Amazon Brasil. Não expira. Entrega automática após confirmação do pagamento. Garantia KIYVO de 7 dias.",
    "preco": 94.9,
    "preco_de": 100,
    "categoria": "giftcards",
    "tipo": "giftcard",
    "vendedor_nome": "Gift Cards BR",
    "vendor_id": "gift-cards-br",
    "gradient": "from-lime-500 to-green-700",
    "emoji": "📦",
    "imagem_capa": null,
    "rating": 4.8,
    "total_reviews": 474,
    "total_vendas": 8459,
    "boost": false,
    "verificado": true,
    "created_at": "2026-07-01T02:44:28.781Z",
    "entrega_automatica": true,
    "garantia_dias": 7
  }
];
