'use client'; import { useState } from 'react'; import { GitCompare } from 'lucide-react'; import { AgentShell, Field, inputClass } from '@/components/agents/AgentShell';
export default function Page(){const[vA,setVA]=useState('Controle A');const[vB,setVB]=useState('Variante B');const[visA,setVisA]=useState('1000');const[convA,setConvA]=useState('25');const[visB,setVisB]=useState('1000');const[convB,setConvB]=useState('38');const[loading,setLoading]=useState(false);const[out,setOut]=useState<any>(null);
const gerar=async()=>{setLoading(true);try{const r=await fetch('/api/agents/abtester',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({variantes:[{nome:vA,visitantes:Number(visA),conversoes:Number(convA)},{nome:vB,visitantes:Number(visB),conversoes:Number(convB)}]})});const d=await r.json();if(d.error)return alert(d.error);setOut(d)}catch{alert('Erro')}finally{setLoading(false)}}
return(<AgentShell titulo="ABTester" tagline="Calculadora de significância estatística p/ testes A/B" icone={<GitCompare className="w-7 h-7"/>} cor="bg-gradient-to-br from-cyan-500 to-teal-600" labelBotao="Calcular resultado" onGerar={gerar} loading={loading} output={out && (
<div className="space-y-3">
<div className={`rounded-2xl p-5 text-white text-center ${out.vencedor?'bg-emerald-500':'bg-slate-500'}`}><p className="text-[11px] font-black uppercase opacity-80">Resultado</p><p className="text-2xl font-black mt-1">{out.vencedor?`🏆 "${out.venced}" venceu!`:'⏳ Inconclusivo'}</p><p className="text-sm mt-1">{out.recomendacao}</p></div>
<div className="space-y-2">{out.resultados.map((r:any,i:number)=>(<div key={i} className={`rounded-xl p-3 border-2 ${r.vencedor?'border-emerald-500 bg-emerald-50 dark:bg-emerald-900/20':'border-slate-200 dark:border-slate-800 bg-white dark:bg-[#111]'}`}><div className="flex items-center justify-between"><p className="font-black">{r.nome} {r.vencedor && '🏆'}</p><p className="text-sm font-bold">{r.conversao.toFixed(2)}%</p></div><div className="h-2 bg-slate-200 dark:bg-slate-700 rounded-full mt-2 overflow-hidden"><div className="h-full bg-brand-500" style={{width:`${Math.min(100,r.conversao*20)}%`}}/></div><p className="text-[10px] text-slate-500 mt-1">IC 95%: {r.icInferior.toFixed(2)}% – {r.icSuperior.toFixed(2)}%{r.liftPercent?` • lift ${r.liftPercent>=0?'+':''}${r.liftPercent.toFixed(1)}%`:''}</p></div>))}</div>
<p className="text-xs text-slate-500">Confiança: {out.confianca}% • Dias recomendados: {out.diasRecomendados} • Volume suficiente: {out.diasTesteSuficientes?'✅':'❌'}</p>
</div>)}>
<div className="grid grid-cols-3 gap-2"><Field label="Nome A"><input className={inputClass} value={vA} onChange={e=>setVA(e.target.value)}/></Field><Field label="Visitas A"><input className={inputClass} type="number" value={visA} onChange={e=>setVisA(e.target.value)}/></Field><Field label="Conversões A"><input className={inputClass} type="number" value={convA} onChange={e=>setConvA(e.target.value)}/></Field></div>
<div className="grid grid-cols-3 gap-2"><Field label="Nome B"><input className={inputClass} value={vB} onChange={e=>setVB(e.target.value)}/></Field><Field label="Visitas B"><input className={inputClass} type="number" value={visB} onChange={e=>setVisB(e.target.value)}/></Field><Field label="Conversões B"><input className={inputClass} type="number" value={convB} onChange={e=>setConvB(e.target.value)}/></Field></div>
<p className="text-xs text-slate-500">Dica: deixe o teste rodar por pelo menos 7 dias e 1000 visitas/variante SEM OLHAR antes de decidir.</p>
</AgentShell>)}
